"""Automatic application convergence services."""

from .activation import (
    ReleaseActivationBusy,
    ReleaseActivationError,
    ReleaseActivationFailed,
    ReleaseActivationPhase,
    ReleaseActivationRole,
    ReleaseActivationRoleError,
    ReleaseActivationStatus,
    ReleaseActivator,
    ReleaseAdoptionPort,
    ReleaseDrainPort,
    ReleaseHealthPort,
    ReleaseHealthStage,
    ReleaseLaunchPort,
    ReleaseRehearsalPort,
    ReleaseRollbackFailed,
)
from .broker import (
    UpdateBroker,
    UpdateBrokerError,
    UpdateBrokerHandle,
    UpdateBrokerJoinTimeout,
    UpdateBrokerLifecycleError,
    UpdateBrokerPhase,
    UpdateBrokerRole,
    UpdateBrokerRoleError,
    UpdateBrokerStateError,
    UpdateBrokerStatus,
)
from .convergence import ConvergencePhase, UpdateConvergenceService
from .handoff import (
    ActivationOutcome,
    BackendEndpoint,
    SeamlessBackendHandoff,
    health_probe,
    spawn_candidate_backend,
)
from .immutable_store import (
    AcceptedRelease,
    AcceptedReleaseCorruption,
    ActiveReleasePointerCorruption,
    ActiveReleaseState,
    ImmutableReleaseStore,
    ImmutableReleaseStoreError,
    ReleaseIdentityConflict,
    ReleaseStoreAuthorityError,
    ReleaseStoreUninitialized,
)
from .manifest import (
    RELEASE_MANIFEST_NAME,
    RELEASE_MANIFEST_VERSION,
    ReleaseManifest,
    ReleaseManifestError,
    ReleaseMember,
)
from .releases import CandidateIntegrityError, GitReleaseStore, ReleaseCandidate
from .trusted_repository import (
    PinnedRootError,
    ReleaseSetVerificationError,
    RepositoryRefreshError,
    TrustedReleaseRepository,
    TrustedRepositoryError,
    VerifiedReleaseSet,
    verify_local_release_set,
)

__all__ = [
    "ActivationOutcome",
    "AcceptedRelease",
    "AcceptedReleaseCorruption",
    "ActiveReleasePointerCorruption",
    "ActiveReleaseState",
    "BackendEndpoint",
    "CandidateIntegrityError",
    "ConvergencePhase",
    "GitReleaseStore",
    "ImmutableReleaseStore",
    "ImmutableReleaseStoreError",
    "PinnedRootError",
    "RELEASE_MANIFEST_NAME",
    "RELEASE_MANIFEST_VERSION",
    "ReleaseManifest",
    "ReleaseManifestError",
    "ReleaseCandidate",
    "ReleaseActivationBusy",
    "ReleaseActivationError",
    "ReleaseActivationFailed",
    "ReleaseActivationPhase",
    "ReleaseActivationRole",
    "ReleaseActivationRoleError",
    "ReleaseActivationStatus",
    "ReleaseActivator",
    "ReleaseAdoptionPort",
    "ReleaseDrainPort",
    "ReleaseHealthPort",
    "ReleaseHealthStage",
    "ReleaseIdentityConflict",
    "ReleaseLaunchPort",
    "ReleaseMember",
    "ReleaseRehearsalPort",
    "ReleaseRollbackFailed",
    "ReleaseSetVerificationError",
    "ReleaseStoreAuthorityError",
    "ReleaseStoreUninitialized",
    "RepositoryRefreshError",
    "SeamlessBackendHandoff",
    "TrustedReleaseRepository",
    "TrustedRepositoryError",
    "UpdateBroker",
    "UpdateBrokerError",
    "UpdateBrokerHandle",
    "UpdateBrokerJoinTimeout",
    "UpdateBrokerLifecycleError",
    "UpdateBrokerPhase",
    "UpdateBrokerRole",
    "UpdateBrokerRoleError",
    "UpdateBrokerStateError",
    "UpdateBrokerStatus",
    "UpdateConvergenceService",
    "VerifiedReleaseSet",
    "health_probe",
    "spawn_candidate_backend",
    "verify_local_release_set",
]
