"""Crash-safe workflow primitives for Stockroom's future zero-touch pipeline.

The package is intentionally isolated from the current API job runner, PartRecord,
and capture/enrich/ingest orchestrators.  Integration will happen through later
adapters after this state machine has proved durable on its own.
"""

from .model import (
    BatchCancellationRecord,
    BatchCancellationState,
    BatchRecord,
    BatchStatus,
    ComponentPublicationReceipt,
    DecisionKind,
    DecisionRecord,
    DecisionStatus,
    IntakeIdentity,
    ItemComponentBinding,
    ItemRecord,
    ItemStatus,
    PublicationCompletionDisposition,
    PublicationLease,
    PublicationMembership,
    PublicationMembershipState,
    PublicationOperation,
    PublicationReceipt,
    PublicationState,
    ResolvedComponent,
    StageRecord,
    StageStatus,
    WorkflowConflict,
    WorkflowDataCorruption,
    WorkflowEvent,
)
from .planner import (
    WORKFLOW_GRAPH_VERSION,
    StageName,
    StageSpec,
    default_stage_plan,
)
from .runtime import (
    CompletionOutcome,
    DecisionOutcome,
    DispatchRecord,
    ExactIdentityOutcome,
    FrozenJson,
    InvalidStageOutcome,
    PermanentFailureOutcome,
    PriorStageResults,
    PublicationProposalOutcome,
    RetryOutcome,
    StageContext,
    StageHandler,
    StageHandlerError,
    StageHandlerRegistry,
    StageOutcome,
    WorkflowRuntime,
)
from .store import WorkflowStore

__all__ = [
    "BatchCancellationRecord",
    "BatchCancellationState",
    "BatchRecord",
    "BatchStatus",
    "ComponentPublicationReceipt",
    "CompletionOutcome",
    "DecisionKind",
    "DecisionOutcome",
    "DecisionRecord",
    "DecisionStatus",
    "DispatchRecord",
    "ExactIdentityOutcome",
    "FrozenJson",
    "IntakeIdentity",
    "InvalidStageOutcome",
    "ItemComponentBinding",
    "ItemRecord",
    "ItemStatus",
    "PermanentFailureOutcome",
    "PriorStageResults",
    "PublicationCompletionDisposition",
    "PublicationLease",
    "PublicationMembership",
    "PublicationMembershipState",
    "PublicationOperation",
    "PublicationProposalOutcome",
    "PublicationReceipt",
    "PublicationState",
    "ResolvedComponent",
    "RetryOutcome",
    "StageContext",
    "StageHandler",
    "StageHandlerError",
    "StageHandlerRegistry",
    "StageName",
    "StageOutcome",
    "StageRecord",
    "StageSpec",
    "StageStatus",
    "WorkflowConflict",
    "WorkflowDataCorruption",
    "WorkflowEvent",
    "WorkflowRuntime",
    "WorkflowStore",
    "WORKFLOW_GRAPH_VERSION",
    "default_stage_plan",
]
