"""The EDA tool registry: the ONE place a tool's facts live.

Owner directive (2026-07-24): "i dont want any major system to be overly specific to one
thing just that our app can handle whatever." KiCad and Altium really are different; that
difference belongs HERE, as data, so every other subsystem stays generic and adding a third
tool is adding a registry entry rather than editing ten call sites.

This module is deliberately dependency-free and Qt-free so anything may import it.

The first consumer is workspace hygiene -- the generated `.gitignore` / `.gitattributes` for
a synced workspace. That is not busywork: the measured cause of the owner's KiCad peer-sync
failures was that nothing ignored KiCad's PER-USER files (`.kicad_prl` holds one user's
window state, `fp-info-cache` is a regenerated machine cache). Committed, they mutate on
every open, so two peers conflict on every pull while the actual design sources merge
perfectly. KiCad's own documentation says not to commit them. Generating these files from
the registry means no human has to remember any of it, for any tool.
"""
from __future__ import annotations

from dataclasses import dataclass, field

GENERATED_HEADER = (
    "# Generated by Stockroom from its EDA tool registry -- do not hand-edit.\n"
    "# Regenerate instead; hand edits are overwritten. Rules come from each tool's\n"
    "# adapter in stockroom/eda/registry.py.\n"
)


@dataclass(frozen=True)
class EdaTool:
    """Everything generic code needs to know about one EDA tool.

    A capability a tool LACKS is data here, never an `if tool == "altium"` branch buried in
    shared logic.
    """

    key: str
    label: str
    # Per-user or machine-generated files. Committing these is what makes two peers
    # conflict on every pull, so they are ignored in any synced workspace.
    ignore: tuple[str, ...] = ()
    # Formats that must never be text-normalized and must never be auto-merged. In git,
    # `binary` is shorthand for `-diff -merge -text`, so marking them also turns an
    # unmergeable-format collision into a LOUD conflict instead of a corrupted file.
    binary: tuple[str, ...] = ()
    # Formats that ARE text and must not be misdetected as binary (they diff and merge
    # normally, and we want that).
    text: tuple[str, ...] = ()
    # Asset kinds this tool consumes. Generic readiness/capture code iterates these rather
    # than hardcoding "symbol, footprint, model".
    asset_kinds: tuple[str, ...] = ("symbol", "footprint", "model")
    # Asset kinds the tool CANNOT be given through Stockroom's normal reference mechanism,
    # mapped to why. Generic code reads this instead of special-casing a tool.
    unsupported_assets: dict[str, str] = field(default_factory=dict)


_KICAD = EdaTool(
    key="kicad",
    label="KiCad",
    ignore=(
        "*.kicad_prl",  # PROJECT-LOCAL per-user settings; KiCad's docs say do not commit
        "fp-info-cache",  # regenerated footprint cache, machine-specific and large
        "*.lck",  # editor lock files
        "*-backups/",  # KiCad's automatic backup archives
        "*.kicad_sch-bak",
        "*.kicad_pcb-bak",
        "_autosave-*",
        "*.000",  # legacy rescue/backup artifacts
    ),
    # KiCad's design sources are all s-expression TEXT and must stay diffable/mergeable.
    text=(
        "*.kicad_sch",
        "*.kicad_pcb",
        "*.kicad_sym",
        "*.kicad_mod",
        "*.kicad_pro",
        "*.kicad_wks",
        "*.kicad_dru",
        "*.net",
    ),
    binary=("*.wrl", "*.step", "*.stp"),
)

_ALTIUM = EdaTool(
    key="altium",
    label="Altium Designer",
    ignore=(
        "History/",  # Altium's local revision history folder
        "__Previews/",
        "Project Logs for*/",
        "Project Outputs for*/",
        "*.$$$",
        "*.PcbDoc.bak*",
        "*.SchDoc.bak*",
    ),
    # OLE2 compound documents: unmergeable, and a line-ending rewrite is unrecoverable.
    binary=(
        "*.PcbLib",
        "*.SchLib",
        "*.IntLib",
        "*.PcbDoc",
        "*.SchDoc",
        "*.PcbLib3D",
    ),
    # INI-style text -- the DbLib is emitted as deterministic INI by altium/dblib.py, so
    # marking it binary would destroy the diffability that makes review possible.
    text=("*.DbLib", "*.PrjPcb", "*.PrjScr", "*.OutJob"),
    # Altium takes a 3D model as a 3D Body object INSIDE the footprint's .PcbLib binary,
    # so no database/reference mechanism can carry it. Verified 2026-07-24; see the ledger
    # FINDINGS block. Generic readiness code reads this rather than special-casing Altium.
    unsupported_assets={
        "model": (
            "Altium stores 3D as a 3D Body inside the footprint's .PcbLib (an OLE2 "
            "binary), so it cannot be attached by reference; it must be embedded."
        )
    },
)

_REGISTRY: dict[str, EdaTool] = {t.key: t for t in (_KICAD, _ALTIUM)}


def all_tools() -> tuple[EdaTool, ...]:
    """Every registered tool, in a stable order."""
    return tuple(_REGISTRY[k] for k in sorted(_REGISTRY))


def get_tool(key: str) -> EdaTool:
    """Look up a tool. Raises KeyError on an unknown key -- never falls back to a default,
    because a silent fallback to KiCad is exactly what produced the attach-clobber bug."""
    try:
        return _REGISTRY[key]
    except KeyError:
        known = ", ".join(sorted(_REGISTRY))
        raise KeyError(f"unknown EDA tool {key!r}; known tools: {known}") from None


def _resolve(keys, extra_tools) -> list[EdaTool]:
    """Registered tools for `keys`, plus any ad-hoc `extra_tools`, deduped and ordered by
    key so generated output is deterministic and never churns between runs."""
    tools = {get_tool(k).key: get_tool(k) for k in (keys or ())}
    for tool in extra_tools or ():
        tools[tool.key] = tool
    return [tools[k] for k in sorted(tools)]


def _dedupe(items) -> list[str]:
    """Preserve first-seen order while dropping duplicates, so two tools claiming the same
    pattern emit it once."""
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            out.append(item)
    return out


def workspace_gitignore(keys=(), *, extra_tools=()) -> str:
    """The `.gitignore` for a workspace holding files for `keys`.

    Only per-user and generated artifacts are listed. Design SOURCES are never ignored --
    ignoring them is how a peer ends up with a project that will not open.
    """
    tools = _resolve(keys, extra_tools)
    lines = [GENERATED_HEADER]
    for tool in tools:
        if not tool.ignore:
            continue
        lines.append(f"# {tool.label}: per-user and generated files (never design sources)")
        lines.extend(_dedupe(tool.ignore))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def workspace_gitattributes(keys=(), *, extra_tools=()) -> str:
    """The `.gitattributes` for a workspace holding files for `keys`.

    `binary` (= `-diff -merge -text`) both protects the bytes and makes git refuse to
    auto-merge a format that cannot be merged, which turns silent corruption into a
    conflict a human can actually resolve.
    """
    tools = _resolve(keys, extra_tools)
    lines = [GENERATED_HEADER]
    for tool in tools:
        if not (tool.binary or tool.text):
            continue
        lines.append(f"# {tool.label}")
        for pattern in _dedupe(tool.text):
            lines.append(f"{pattern} text eol=lf")
        for pattern in _dedupe(tool.binary):
            lines.append(f"{pattern} binary")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"
