"""The EDA tool registry: the ONE place a tool's facts live.

Owner directive (2026-07-24): "i dont want any major system to be overly specific to one
thing just that our app can handle whatever." KiCad and Altium really are different; that
difference belongs HERE, as data, so every other subsystem stays generic and adding a third
tool is adding a registry entry rather than editing ten call sites.

This module is deliberately dependency-free and Qt-free so anything may import it.

The first consumer is workspace hygiene -- the generated `.gitignore` / `.gitattributes` for
a synced workspace. That is not busywork: the measured cause of the owner's KiCad peer-sync
failures was that nothing ignored KiCad's PER-USER files (`.kicad_prl` holds one user's
window state, `fp-info-cache` is a regenerated machine cache). Committed, they mutate on
every open, so two peers conflict on every pull while the actual design sources merge
perfectly. KiCad's own documentation says not to commit them. Generating these files from
the registry means no human has to remember any of it, for any tool.
"""
from __future__ import annotations

from dataclasses import dataclass, field

GENERATED_HEADER = (
    "# Generated by Stockroom from its EDA tool registry -- do not hand-edit.\n"
    "# Regenerate instead; hand edits are overwritten. Rules come from each tool's\n"
    "# adapter in stockroom/eda/registry.py.\n"
)


@dataclass(frozen=True)
class PlacementBinding:
    """How a PLACED component in this tool's design files carries the id of the Stockroom
    library part it is bound to.

    A binding is what makes an assignment durable: a designator is renumbered by annotation
    and a Value is edited freely, so neither can key the link. `field` is the placement field
    that holds the part id; `writable` says whether Stockroom can put it there itself.

    `writable=False` is not a missing feature, it is a fact about the tool, and it decides
    where the binding is STORED: a tool Stockroom can write carries its binding inside the
    design (atomic with the same byte-preserving write, and it travels with the file), while
    a tool Stockroom can only read keeps it on the Stockroom project record instead.
    """

    field: str = "Stockroom ID"
    writable: bool = False
    # Why the design cannot be written, shown to the user rather than left as silence.
    reason: str = ""


@dataclass(frozen=True)
class EmbeddedAsset:
    """An asset kind this tool can only receive by having the TOOL ITSELF write it into a
    binary container the part already owns.

    This is a different fact from `unsupported_assets`, and conflating them is what kept
    Altium 3D permanently out of reach. Both are true of an Altium 3D model at once:

    - it cannot be given BY REFERENCE (no database column or path carries a 3D body), which is
      what `unsupported_assets` records, and it is why a capture session must never be asked to
      fetch one;
    - it CAN be obtained, by driving the tool to embed the model file the part already holds,
      which is what this records, and it is why the gap is worth reporting.

    So a kind listed here is a CLOSABLE gap. That distinction matters: reporting a gap that can
    never be closed is exactly what "CAD Incomplete forever" looked like, while hiding a gap that
    CAN be closed is how Altium parts silently shipped with no 3D at all.
    """

    # The asset whose file receives the payload (an Altium 3D body lives in the footprint's
    # `.PcbLib`), and the asset kind that SUPPLIES the payload. The source is normally the same
    # kind held for another tool: one STEP file serves every tool, so nothing is captured twice.
    container: str = "footprint"
    source: str = "model"
    # Embedding runs the real EDA tool, so it needs that tool installed on THIS machine. Stated
    # as data because a KiCad-only peer must be told why the action is unavailable rather than
    # watching it silently do nothing.
    requires_tool_installed: bool = True
    reason: str = ""


@dataclass(frozen=True)
class PathContract:
    """How this tool makes a library reference resolve to the same asset on every machine.

    A project stores references to library symbols, footprints and 3D models, and a library lives
    at a different absolute path on every peer's disk. Whether a stored reference survives that is
    a fact about the TOOL, not about any one surface, so it belongs here: KiCad resolves through a
    path VARIABLE it holds in its own config, while Altium's .DbLib carries an absolute data-source
    path and so is rebuilt on each machine instead of travelling.

    Generic code (the library-version pin surface, the doctor, onboarding) reads this instead of
    knowing that `SR_LIB` is a KiCad concept.
    """

    # "env_var": the tool resolves through a named variable that must be set on each machine.
    # "relative": references are relative to the library folder, so nothing has to be set.
    # "derived": the file carrying the references is machine-specific, so Stockroom REGENERATES it
    #   locally. Nothing to set, but the rebuild is not optional. Do not conflate this with
    #   "relative": that one promises the artifact travels as it stands, which for a .DbLib is the
    #   exact belief that shipped a library nobody could connect to (see _ALTIUM.path_contract).
    kind: str = "relative"
    # The variable's name, and the tool config file Stockroom writes it into, for an honest
    # message when it is missing. Empty for a relative contract.
    variable: str = ""
    config_file: str = ""
    # What a portable reference literally starts with, so a surface can SHOW the shape.
    prefix: str = ""
    description: str = ""


@dataclass(frozen=True)
class DataField:
    """One piece of RECORD data a tool receives when a part is placed from the library.

    This is the answer to "what does an EDA tool actually get from this part", and it is the
    registry's job because the answer differs per tool: KiCad takes five schematic properties, while
    an Altium DbLib row carries commercial columns (price, stock, lifecycle) that KiCad has no
    property for. Before this existed the same question was answered independently by
    `altium/dblib.FIELD_MAP`, `altium/datasource.ALTIUM_COLUMNS` and `projects/fill.COMPLETION_FIELDS`,
    so a column added in one place was silently missing from the others.

    ASSET references are deliberately in scope (`footprint` for KiCad): a schematic property holding
    a footprint ref is data the tool receives exactly like an MPN is, and the surface that reports
    the handoff must not draw an arbitrary line through it.
    """

    # The record-derived value this carries. Lower-case, stable, and the key generic code and the
    # frontend both join on - never the tool's own spelling, which differs between tools.
    key: str
    # What a PERSON calls it. Shared across tools so one field is one row in the union.
    label: str
    # What THIS tool calls it: a `.kicad_sch` property name, or an Altium Design Parameter. Altium's
    # bracket syntax is meaningful (a bracketed name is a reserved model/attribute binding, a bare
    # one is an ordinary parameter), so it is carried verbatim rather than derived from the label.
    tool_field: str
    # Whether the tool shows this on the placed component by default (Altium's VisibleOnAdd).
    visible: bool = False
    # Whether a PLACED component can be measured as missing this. Nearly always true.
    #
    # False is for a field the tool receives structurally rather than as a fillable property: a
    # KiCad component's symbol arrives as its `lib_id`, and a component cannot exist without one,
    # so "components missing a symbol" is not a countable thing and a completion passport that
    # counted it would report a gap no action could ever close. The field is still declared,
    # because the handoff band must say the symbol reaches KiCad - leaving it out was the
    # alternative, and it made the surface claim symbols go to Altium alone.
    passport: bool = True


# WHO OWNS a field's value. Declared ONCE, globally, rather than per tool: "a price comes from a
# vendor" is a fact about the field itself and is equally true for every tool that carries it, so a
# per-tool flag would be the same answer written twice with a chance to disagree.
#
# Three origins, because there really are three and collapsing them misleads:
#
#   "curated" - a PERSON maintains it. These are the fields the detail sheet's handoff band shows
#       and offers to edit, because they are the ones somebody is responsible for getting right.
#   "vendor"  - a DISTRIBUTOR supplies it and a Refresh overwrites it. Already the Sourcing
#       column's whole subject, with a vendor attribution and a refresh control there, and it
#       changes on its own between sessions. Repeating it at the top of the sheet would be both
#       duplication and a lie about who owns the value.
#   "derived" - COMPUTED from other record fields when the artifact is emitted, and never stored.
#       An Altium `Value` column is a passive's parametric value or an active's MPN, worked out at
#       emit time by `ingest.component_naming.derive_value`. There is no stored value to show and
#       nothing to edit, and re-deriving it in the frontend to fill a cell would fork that rule
#       into a second implementation that drifts - which is exactly what this registry exists to
#       prevent. So the band omits it rather than guessing.
#
# A field absent from this map is "curated", which is the safe default: it appears, and somebody
# notices it should not, rather than silently vanishing from the surface.
FIELD_ORIGINS: dict[str, str] = {
    "supplier": "vendor",
    "supplier_part_number": "vendor",
    "supplier_url": "vendor",
    "price": "vendor",
    "stock": "vendor",
    "lifecycle": "vendor",
    "value": "derived",
}


@dataclass(frozen=True)
class UnionField:
    """One row of `data_field_union`: a field, and every tool that consumes it."""

    key: str
    label: str
    # Registry declaration order, so a surface can say "KiCad and Altium" in a stable order.
    tools: tuple[str, ...]
    # Who owns this value: "curated" | "vendor" | "derived". See FIELD_ORIGINS for what each
    # means and why it is one global declaration rather than a per-tool flag.
    origin: str = "curated"


@dataclass(frozen=True)
class EdaTool:
    """Everything generic code needs to know about one EDA tool.

    A capability a tool LACKS is data here, never an `if tool == "altium"` branch buried in
    shared logic.
    """

    key: str
    label: str
    # Stable machine-readiness checks and the Settings anchor that owns their repair. Primary EDA
    # policy reads these instead of branching on tool keys. A future tool declares its own setup
    # contract here and immediately participates in onboarding and Settings DTOs.
    setup_checks: tuple[str, ...] = ()
    settings_target: str = ""
    # Per-user or machine-generated files. Committing these is what makes two peers
    # conflict on every pull, so they are ignored in any synced workspace.
    ignore: tuple[str, ...] = ()
    # Formats that must never be text-normalized and must never be auto-merged. In git,
    # `binary` is shorthand for `-diff -merge -text`, so marking them also turns an
    # unmergeable-format collision into a LOUD conflict instead of a corrupted file.
    binary: tuple[str, ...] = ()
    # Formats that ARE text and must not be misdetected as binary (they diff and merge
    # normally, and we want that).
    text: tuple[str, ...] = ()
    # Patterns whose CONTENT belongs in git-lfs rather than in the git object database. Every
    # captured part otherwise adds a permanent, un-GC-able copy to history for every future cloner,
    # so a growing binary library makes every clone slower forever. Must be a SUBSET of `binary`:
    # a text format sent to LFS would stop diffing, which is the opposite of what it is for.
    lfs: tuple[str, ...] = ()
    # The subset of `lfs` that also gets git-lfs's check-out semantics (`lockable`): the file is
    # checked out READ-ONLY and only becomes writable to whoever holds the lock, which is the real
    # answer to "two people, never any errors" on a format nothing can merge.
    #
    # MEASURED 2026-07-25, and it decides what may appear here: a lockable file really is
    # `-r--r--r--` on disk, and `git lfs lock` FAILS outright (`missing protocol: ""`) on a repo
    # with no remote. So only files STOCKROOM ITSELF NEVER WRITES may be listed, or the app would
    # break its own operations (the Altium 3D embed writes into the .PcbLib), and emitting it at
    # all is gated on a live probe rather than assumed.
    lockable: tuple[str, ...] = ()
    # Files STOCKROOM ITSELF generates from the library records for this tool, and can regenerate
    # at any time. Kept apart from `ignore` because the two are different facts with different
    # remedies: a per-user file is somebody's window state and is gone for good, while a derived
    # file is rebuilt on demand. Sharing a derived artifact through git is worse than useless when
    # it is BINARY: two peers who each add a different part produce two unmergeable files carrying
    # no information the records do not already hold, so every such conflict is pure noise on a
    # file that can be recreated in milliseconds.
    derived: tuple[str, ...] = ()
    # Asset kinds this tool consumes. Generic readiness/capture code iterates these rather
    # than hardcoding "symbol, footprint, model".
    asset_kinds: tuple[str, ...] = ("symbol", "footprint", "model")
    # Asset kinds the tool CANNOT be given through Stockroom's normal reference mechanism,
    # mapped to why. Generic code reads this instead of special-casing a tool.
    unsupported_assets: dict[str, str] = field(default_factory=dict)
    # Asset kinds the tool takes only by EMBEDDING (see EmbeddedAsset). A kind may appear here
    # AND in `unsupported_assets`: it cannot be referenced, but it can be embedded.
    embedded_assets: dict[str, EmbeddedAsset] = field(default_factory=dict)
    # Record data this tool receives on placement, in the order the tool's own artifact declares it
    # (see DataField). Generic code and the detail sheet's handoff band iterate this; the Altium
    # DbLib column map and KiCad's completion passport are both DERIVED from it.
    data_fields: tuple[DataField, ...] = ()
    # How a placed component carries the library part it is bound to (see PlacementBinding).
    placement_binding: PlacementBinding = PlacementBinding()
    # How this tool's stored library references stay portable across machines (see PathContract).
    path_contract: PathContract = PathContract()

    # WHICH FORMS OF A DATASHEET THIS TOOL CAN ACTUALLY OPEN, best first.
    #
    #   "file" - a datasheet PDF stored in the library, referenced so the tool resolves it on any
    #            machine. Only a tool with a path contract that survives the trip can offer this.
    #   "url"  - the vendor's link. Always resolvable, always a round trip to the internet.
    #
    # A fact about the TOOL, so it lives here rather than as two hand-written orders in two
    # modules - which is what it was, and they had drifted into opposites. KiCad resolves
    # `${SR_LIB}/datasheets/<file>` through a path variable it holds in its own config, so a local
    # file is BETTER there. A .DbLib link column carries a plain string with no such variable, so
    # Altium can use a URL and nothing else - and the old fallback put a bare "X.pdf" in that
    # column, a link that resolves to nothing while the row still said "Datasheet" beside it.
    #
    # A form this tool cannot use is simply ABSENT here, so generic code offers nothing rather
    # than something broken. Adding a third tool is a registry entry, never a branch.
    datasheet_sources: tuple[str, ...] = ("url",)

    def ignored_patterns(self) -> tuple[str, ...]:
        """Every pattern this tool contributes to a workspace `.gitignore`, per-user AND derived.

        Generic code must read THIS rather than `ignore`, or a derived file that is already
        committed stays committed forever while the generated rules claim it is ignored (an ignore
        rule has no effect on a tracked file, which is the whole reason hygiene untracks).
        """
        return tuple(self.ignore) + tuple(self.derived)

    def capturable_assets(self) -> tuple[str, ...]:
        """Kinds a CAPTURE session can fetch by reference, in registered order.

        An embeddable kind is excluded: the payload comes from a file the part already holds, so
        asking a vendor for a second, tool-specific copy would be busywork.
        """
        return tuple(k for k in self.asset_kinds if k not in self.unsupported_assets)

    def closable_assets(self) -> tuple[str, ...]:
        """Kinds a part can actually END UP holding, in registered order.

        This is what readiness reports on, and it is deliberately wider than
        `capturable_assets`: a kind that cannot be referenced but CAN be embedded is a real gap
        with a real action behind it, so hiding it would be dishonest.
        """
        return tuple(
            k
            for k in self.asset_kinds
            if k not in self.unsupported_assets or k in self.embedded_assets
        )


_KICAD = EdaTool(
    key="kicad",
    label="KiCad",
    setup_checks=("installation", "catalog_wiring"),
    settings_target="settings.kicad",
    # A stored PDF wins: KiCad resolves `${SR_LIB}/datasheets/<file>` through the path variable it
    # holds in its own config, so the local copy opens instantly and works with no network. The
    # vendor URL is the fallback for a part whose PDF was never fetched.
    datasheet_sources=("file", "url"),
    ignore=(
        "*.kicad_prl",  # PROJECT-LOCAL per-user settings; KiCad's docs say do not commit
        "fp-info-cache",  # regenerated footprint cache, machine-specific and large
        "*.lck",  # editor lock files
        "*-backups/",  # KiCad's automatic backup archives
        "*.kicad_sch-bak",
        "*.kicad_pcb-bak",
        "_autosave-*",
        "*.000",  # legacy rescue/backup artifacts
    ),
    # KiCad's design sources are all s-expression TEXT and must stay diffable/mergeable.
    text=(
        "*.kicad_sch",
        "*.kicad_pcb",
        "*.kicad_sym",
        "*.kicad_mod",
        "*.kicad_pro",
        "*.kicad_wks",
        "*.kicad_dru",
        "*.net",
    ),
    binary=("*.wrl", "*.step", "*.stp"),
    # The 3D models are the only KiCad payload that is genuinely binary and genuinely grows: a
    # STEP file is megabytes and every captured part adds one. Nothing here is lockable, because
    # Stockroom writes the models itself (ingest, doctor repair, capture).
    lfs=("*.wrl", "*.step", "*.stp"),
    # Exactly the properties `projects/fill.proposed_changes` stamps onto a placed component, in
    # the order it writes them. `Footprint` is here because a schematic Footprint property is data
    # KiCad receives from the record just as the MPN is. KiCad has no property for price, stock or
    # lifecycle, which is why those appear only under Altium.
    data_fields=(
        DataField(key="mpn", label="MPN", tool_field="MPN", visible=True),
        DataField(key="manufacturer", label="Manufacturer", tool_field="Manufacturer"),
        DataField(key="datasheet", label="Datasheet", tool_field="Datasheet"),
        DataField(key="description", label="Description", tool_field="Description"),
        DataField(key="footprint", label="Footprint", tool_field="Footprint"),
        # KiCad receives the symbol as the placed component's `lib_id`, not as a fillable
        # property, so it is declared (the handoff band must show that symbols do reach KiCad)
        # but excluded from the completion passport - see DataField.passport.
        DataField(key="symbol", label="Symbol", tool_field="lib_id", passport=False),
    ),
    # Stockroom edits .kicad_sch through the byte-preserving sexp layer, so a KiCad binding
    # lives in the schematic itself: written in the SAME transaction as the fill it records,
    # untouched by annotation, and carried to a peer by the project's own git.
    placement_binding=PlacementBinding(field="Stockroom ID", writable=True),
    # KiCad stores library references as `${SR_LIB}/...`, and resolves SR_LIB from its own
    # kicad_common.json, which `kicad/wiring.py` points at the active profile folder. That is what
    # makes a schematic committed on one machine resolve on a peer's, so a peer whose SR_LIB is
    # unset or stale gets broken symbols with no error from git.
    path_contract=PathContract(
        kind="env_var",
        variable="SR_LIB",
        config_file="kicad_common.json",
        prefix="${SR_LIB}/",
        description=(
            "KiCad resolves every Stockroom library reference through the SR_LIB path variable, "
            "which Stockroom writes into kicad_common.json to point at the active profile folder. "
            "A peer whose SR_LIB is unset or points elsewhere resolves different files, or none."
        ),
    ),
)

_ALTIUM = EdaTool(
    key="altium",
    label="Altium Designer",
    setup_checks=("installation", "odbc", "catalog_connection"),
    settings_target="settings.altium",
    ignore=(
        "History/",  # Altium's local revision history folder
        "__Previews/",
        "Project Logs for*/",
        "Project Outputs for*/",
        "*.$$$",
        "*.PcbDoc.bak*",
        "*.SchDoc.bak*",
    ),
    # The SQLite data source the .DbLib reads is emitted from the JSON records by
    # altium/datasource.py. It was committed until 2026-07-25 so a fresh clone was placeable with
    # no regenerate step; that traded one real benefit for a worse one. MEASURED: SQLite stamps its
    # own library version into the file header, so two peers on different SQLite builds emit
    # DIFFERENT BYTES for identical content (Windows py 3.14.6 ships SQLite 3.50.4, this WSL venv
    # 3.45.1, and the two files differ at offsets 98-99). And even a perfectly deterministic emit
    # would still conflict, because two peers adding DIFFERENT parts genuinely produce different
    # content in a binary git cannot merge. The clone stays placeable because
    # LibraryOps.ensure_altium_datasource rebuilds it whenever it is missing or stale.
    # The .DbLib joined it 2026-07-26, SUPERSEDING the decision that it "stays shared because it is
    # deterministic INI text a human reviews". That decision rested on the file being PORTABLE, and
    # it is not: real Altium (AD26) cannot open a data source named by a relative path, because the
    # SQLite ODBC driver resolves one against the process working directory and Altium's is never
    # the .DbLib's folder. The connection must therefore carry a MACHINE-SPECIFIC absolute path
    # (Altium's own writer does the same), which a shared file cannot hold. See altium/dblib.py for
    # the measurement. What a human reviews is now the emitter and its FIELD_MAP, in this repo.
    derived=("stockroom-parts.db", "Stockroom.DbLib"),
    # OLE2 compound documents: unmergeable, and a line-ending rewrite is unrecoverable.
    binary=(
        "*.PcbLib",
        "*.SchLib",
        "*.IntLib",
        "*.PcbDoc",
        "*.SchDoc",
        "*.PcbLib3D",
    ),
    # Every Altium payload is an OLE2 compound document, so all of them belong in LFS.
    lfs=(
        "*.PcbLib",
        "*.SchLib",
        "*.IntLib",
        "*.PcbDoc",
        "*.SchDoc",
        "*.PcbLib3D",
    ),
    # Only the DESIGN documents. They are the files two people genuinely fight over, and Stockroom
    # only ever READS them. The libraries are deliberately absent: Stockroom writes a .PcbLib when
    # it embeds a 3D body and a .SchLib when it attaches captured assets, and a read-only checkout
    # would make its own operations fail with a permission error.
    lockable=("*.PcbDoc", "*.SchDoc"),
    # INI-style text -- the DbLib is emitted as deterministic INI by altium/dblib.py, so
    # marking it binary would destroy the diffability that makes review possible.
    text=("*.DbLib", "*.PrjPcb", "*.PrjScr", "*.OutJob"),
    # Altium takes a 3D model as a 3D Body object INSIDE the footprint's .PcbLib binary,
    # so no database/reference mechanism can carry it. Verified 2026-07-24; see the ledger
    # FINDINGS block. Generic readiness code reads this rather than special-casing Altium.
    unsupported_assets={
        "model": (
            "Altium stores 3D as a 3D Body inside the footprint's .PcbLib (an OLE2 "
            "binary), so it cannot be attached by reference; it must be embedded."
        )
    },
    # ... but it CAN be embedded, verified end to end 2026-07-25 (`stockroom.altium.embed3d`):
    # Altium itself is driven to write the 3D body into the footprint's own .PcbLib, and the result
    # is checked by reading the container back from OUTSIDE Altium. So the 3D gap is now REPORTED
    # and has a real action behind it, instead of being hidden as impossible.
    embedded_assets={
        "model": EmbeddedAsset(
            container="footprint",
            source="model",
            requires_tool_installed=True,
            reason=(
                "A 3D body is written into the footprint's .PcbLib by Altium itself, so "
                "embedding needs Altium installed on this machine."
            ),
        )
    },
    # The record data an Altium DbLib row carries onto a placed component. Altium receives strictly
    # MORE than KiCad: a schematic has no property for a supplier's stock level, while a DbLib row
    # does, and that asymmetry is exactly why this is per-tool rather than one global list.
    #
    # This declares the record DATA, not the .DbLib's column LAYOUT - see `altium/dblib.FIELD_MAP`
    # for the wire format, which additionally carries paired columns (an asset ref splits into
    # Ref + Path, a datasheet into a link Description + URL) and the placement binding. The two are
    # tied together by `tests/backend/eda/test_data_fields.py`, which fails if either grows a field
    # the other does not account for.
    data_fields=(
        DataField(key="mpn", label="MPN", tool_field="MPN", visible=True),
        DataField(key="value", label="Value", tool_field="Value", visible=True),
        DataField(key="manufacturer", label="Manufacturer", tool_field="Manufacturer", visible=True),
        DataField(key="description", label="Description", tool_field="[Description]", visible=True),
        DataField(key="datasheet", label="Datasheet", tool_field="ComponentLink1URL"),
        DataField(key="supplier", label="Supplier", tool_field="Supplier"),
        DataField(key="supplier_part_number", label="Supplier Part Number",
                  tool_field="SupplierPartNumber"),
        DataField(key="supplier_url", label="Supplier Link", tool_field="SupplierURL"),
        DataField(key="price", label="Price", tool_field="Price"),
        DataField(key="stock", label="Stock", tool_field="Stock"),
        DataField(key="lifecycle", label="Lifecycle", tool_field="Lifecycle"),
        DataField(key="category", label="Category", tool_field="Category"),
        DataField(key="symbol", label="Symbol", tool_field="[Library Ref]"),
        DataField(key="footprint", label="Footprint", tool_field="[Footprint Ref]"),
    ),
    # A .SchDoc is an OLE2 binary Stockroom reads and never writes, so it cannot stamp a
    # binding onto an existing placement; the binding is kept on the project record instead.
    # A component placed from Stockroom's own DbLib still arrives carrying this parameter,
    # because Altium copies the DbLib column onto the placement itself.
    placement_binding=PlacementBinding(
        field="Stockroom ID",
        writable=False,
        reason=(
            "A .SchDoc is an OLE2 binary that Stockroom reads but never writes, so an "
            "assignment is recorded by Stockroom rather than stamped into the schematic."
        ),
    ),
    # The generated .DbLib names its SQLite data source by an ABSOLUTE path (see altium/dblib.py),
    # so the file is machine-specific and Stockroom rebuilds it locally rather than sharing it.
    # This read `kind="relative"` until 2026-07-26, on the premise that `.\stockroom-parts.db`
    # travels. It does not: `49bde17` measured the SQLite ODBC driver resolving `Database=` against
    # the PROCESS working directory, which is never the library folder, so real Altium answered a
    # relative form with "Connection Failed". The path form was fixed and this contract was not,
    # and it is rendered verbatim to the owner in the library-version card.
    path_contract=PathContract(
        kind="derived",
        prefix="",
        description=(
            "Altium reads this library through a .DbLib naming its data source by an absolute "
            "path, so the file cannot be shared. Stockroom regenerates it on each machine, which "
            "means a peer needs no variable set but must let Stockroom rebuild the .DbLib once. "
            "What a peer still needs is the SQLite ODBC driver Altium reads it through."
        ),
    ),
)

# Declaration order is MEANINGFUL: it is the order tools are offered and reported in, and the
# first entry is the default target. KiCad leads because it is the library Stockroom itself
# writes. Do NOT sort this -- generated FILES are made deterministic by sorting at the point of
# emission (see `_resolve`), which is a separate concern from presentation order.
_REGISTRY: dict[str, EdaTool] = {t.key: t for t in (_KICAD, _ALTIUM)}


def all_tools() -> tuple[EdaTool, ...]:
    """Every registered tool, in declaration order (see `_REGISTRY`)."""
    return tuple(_REGISTRY.values())


def data_field_union() -> tuple[UnionField, ...]:
    """Every record field ANY registered tool consumes, deduplicated, each naming its consumers.

    This is what the detail sheet's handoff band renders: one row per field, saying which tools
    receive it. A third EDA tool joins that band by declaring `data_fields`, with no edit here and
    none in the frontend.

    Order is registry declaration order - the first tool's fields lead, then whatever each later
    tool adds. Deliberately NOT sorted: the order a person reads these in is a registry decision
    (KiCad leads because it is the library Stockroom itself writes), and an alphabetical band would
    open on "Category" rather than the part number.

    The LABEL is the first registered tool's label for the field, so two tools spelling a field
    differently still produce one row with one stable name.
    """
    order: list[str] = []
    labels: dict[str, str] = {}
    consumers: dict[str, list[str]] = {}
    for tool in _REGISTRY.values():
        for f in tool.data_fields:
            if f.key not in consumers:
                order.append(f.key)
                labels[f.key] = f.label
                consumers[f.key] = []
            consumers[f.key].append(tool.key)
    return tuple(
        UnionField(
            key=k,
            label=labels[k],
            tools=tuple(consumers[k]),
            origin=FIELD_ORIGINS.get(k, "curated"),
        )
        for k in order
    )


def default_tool() -> EdaTool:
    """The tool the app targets when the user has not chosen one. Explicit rather than
    "whichever sorts first", which silently made Altium the default once."""
    return next(iter(_REGISTRY.values()))


def get_tool(key: str) -> EdaTool:
    """Look up a tool. Raises KeyError on an unknown key -- never falls back to a default,
    because a silent fallback to KiCad is exactly what produced the attach-clobber bug."""
    try:
        return _REGISTRY[key]
    except KeyError:
        known = ", ".join(sorted(_REGISTRY))
        raise KeyError(f"unknown EDA tool {key!r}; known tools: {known}") from None


def _resolve(keys, extra_tools) -> list[EdaTool]:
    """Registered tools for `keys`, plus any ad-hoc `extra_tools`, deduped and ordered by
    key so generated output is deterministic and never churns between runs."""
    tools = {get_tool(k).key: get_tool(k) for k in (keys or ())}
    for tool in extra_tools or ():
        tools[tool.key] = tool
    return [tools[k] for k in sorted(tools)]


def _dedupe(items) -> list[str]:
    """Preserve first-seen order while dropping duplicates, so two tools claiming the same
    pattern emit it once."""
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            out.append(item)
    return out


def workspace_gitignore(keys=(), *, extra_tools=()) -> str:
    """The `.gitignore` for a workspace holding files for `keys`.

    Only per-user and generated artifacts are listed. Design SOURCES are never ignored --
    ignoring them is how a peer ends up with a project that will not open.
    """
    tools = _resolve(keys, extra_tools)
    lines = [GENERATED_HEADER]
    for tool in tools:
        if tool.ignore:
            lines.append(f"# {tool.label}: per-user and generated files (never design sources)")
            lines.extend(_dedupe(tool.ignore))
            lines.append("")
        # Derived artifacts get their OWN section rather than being folded in above, because the
        # two have different remedies and a person reading the file has to be able to tell them
        # apart: a per-user file is somebody's local state, a derived file is rebuilt on demand.
        if tool.derived:
            lines.append(
                f"# {tool.label}: derived from the library records and regenerated on demand, "
                "so it is never shared"
            )
            lines.extend(_dedupe(tool.derived))
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def workspace_gitattributes(keys=(), *, extra_tools=(), lfs: bool = False,
                            lockable: bool = False) -> str:
    """The `.gitattributes` for a workspace holding files for `keys`.

    `binary` (= `-diff -merge -text`) both protects the bytes and makes git refuse to
    auto-merge a format that cannot be merged, which turns silent corruption into a
    conflict a human can actually resolve.

    `lfs=True` additionally stores the declared binary payloads in git-lfs, so a growing library
    stops adding a permanent copy of every captured part to every future clone. The line emitted is
    `filter=lfs binary`, deliberately NOT the ecosystem's canned
    `filter=lfs diff=lfs merge=lfs -text`. MEASURED 2026-07-25: git-lfs registers no `lfs` merge
    driver, so `merge=lfs` falls back to git's TEXT merge on the POINTER file and writes conflict
    markers inside it, leaving a corrupt pointer that a careless `git add` would commit. Keeping the
    `binary` macro gives LFS storage AND take-ours-and-conflict semantics; `git check-attr` confirms
    the combination resolves to `filter: lfs` with diff/merge/text unset.

    `lockable=True` also marks the tools' declared design documents lockable, which checks them out
    READ-ONLY until the holder takes a lock. It requires `lfs=True` and raises otherwise, because a
    lockable attribute without the filter is inert and would hand back a file that looks configured
    and does nothing.
    """
    if lockable and not lfs:
        raise ValueError(
            "lockable requires lfs: a lockable attribute does nothing without the git-lfs filter"
        )
    tools = _resolve(keys, extra_tools)
    lines = [GENERATED_HEADER]
    for tool in tools:
        if not (tool.binary or tool.text):
            continue
        lines.append(f"# {tool.label}")
        for pattern in _dedupe(tool.text):
            lines.append(f"{pattern} text eol=lf")
        lfs_patterns = set(tool.lfs) if lfs else set()
        lockable_patterns = set(tool.lockable) if lockable else set()
        for pattern in _dedupe(tool.binary):
            if pattern not in lfs_patterns:
                lines.append(f"{pattern} binary")
            elif pattern in lockable_patterns:
                lines.append(f"{pattern} filter=lfs binary lockable")
            else:
                lines.append(f"{pattern} filter=lfs binary")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"
