"""The EDA tool registry: the ONE place a tool's facts live.

Owner directive (2026-07-24): "i dont want any major system to be overly specific to one
thing just that our app can handle whatever." KiCad and Altium really are different; that
difference belongs HERE, as data, so every other subsystem stays generic and adding a third
tool is adding a registry entry rather than editing ten call sites.

This module is deliberately dependency-free and Qt-free so anything may import it.

The first consumer is workspace hygiene -- the generated `.gitignore` / `.gitattributes` for
a synced workspace. That is not busywork: the measured cause of the owner's KiCad peer-sync
failures was that nothing ignored KiCad's PER-USER files (`.kicad_prl` holds one user's
window state, `fp-info-cache` is a regenerated machine cache). Committed, they mutate on
every open, so two peers conflict on every pull while the actual design sources merge
perfectly. KiCad's own documentation says not to commit them. Generating these files from
the registry means no human has to remember any of it, for any tool.
"""
from __future__ import annotations

from dataclasses import dataclass, field

GENERATED_HEADER = (
    "# Generated by Stockroom from its EDA tool registry -- do not hand-edit.\n"
    "# Regenerate instead; hand edits are overwritten. Rules come from each tool's\n"
    "# adapter in stockroom/eda/registry.py.\n"
)


@dataclass(frozen=True)
class PlacementBinding:
    """How a PLACED component in this tool's design files carries the id of the Stockroom
    library part it is bound to.

    A binding is what makes an assignment durable: a designator is renumbered by annotation
    and a Value is edited freely, so neither can key the link. `field` is the placement field
    that holds the part id; `writable` says whether Stockroom can put it there itself.

    `writable=False` is not a missing feature, it is a fact about the tool, and it decides
    where the binding is STORED: a tool Stockroom can write carries its binding inside the
    design (atomic with the same byte-preserving write, and it travels with the file), while
    a tool Stockroom can only read keeps it on the Stockroom project record instead.
    """

    field: str = "Stockroom ID"
    writable: bool = False
    # Why the design cannot be written, shown to the user rather than left as silence.
    reason: str = ""


@dataclass(frozen=True)
class EmbeddedAsset:
    """An asset kind this tool can only receive by having the TOOL ITSELF write it into a
    binary container the part already owns.

    This is a different fact from `unsupported_assets`, and conflating them is what kept
    Altium 3D permanently out of reach. Both are true of an Altium 3D model at once:

    - it cannot be given BY REFERENCE (no database column or path carries a 3D body), which is
      what `unsupported_assets` records, and it is why a capture session must never be asked to
      fetch one;
    - it CAN be obtained, by driving the tool to embed the model file the part already holds,
      which is what this records, and it is why the gap is worth reporting.

    So a kind listed here is a CLOSABLE gap. That distinction matters: reporting a gap that can
    never be closed is exactly what "CAD Incomplete forever" looked like, while hiding a gap that
    CAN be closed is how Altium parts silently shipped with no 3D at all.
    """

    # The asset whose file receives the payload (an Altium 3D body lives in the footprint's
    # `.PcbLib`), and the asset kind that SUPPLIES the payload. The source is normally the same
    # kind held for another tool: one STEP file serves every tool, so nothing is captured twice.
    container: str = "footprint"
    source: str = "model"
    # Embedding runs the real EDA tool, so it needs that tool installed on THIS machine. Stated
    # as data because a KiCad-only peer must be told why the action is unavailable rather than
    # watching it silently do nothing.
    requires_tool_installed: bool = True
    reason: str = ""


@dataclass(frozen=True)
class EdaTool:
    """Everything generic code needs to know about one EDA tool.

    A capability a tool LACKS is data here, never an `if tool == "altium"` branch buried in
    shared logic.
    """

    key: str
    label: str
    # Per-user or machine-generated files. Committing these is what makes two peers
    # conflict on every pull, so they are ignored in any synced workspace.
    ignore: tuple[str, ...] = ()
    # Formats that must never be text-normalized and must never be auto-merged. In git,
    # `binary` is shorthand for `-diff -merge -text`, so marking them also turns an
    # unmergeable-format collision into a LOUD conflict instead of a corrupted file.
    binary: tuple[str, ...] = ()
    # Formats that ARE text and must not be misdetected as binary (they diff and merge
    # normally, and we want that).
    text: tuple[str, ...] = ()
    # Asset kinds this tool consumes. Generic readiness/capture code iterates these rather
    # than hardcoding "symbol, footprint, model".
    asset_kinds: tuple[str, ...] = ("symbol", "footprint", "model")
    # Asset kinds the tool CANNOT be given through Stockroom's normal reference mechanism,
    # mapped to why. Generic code reads this instead of special-casing a tool.
    unsupported_assets: dict[str, str] = field(default_factory=dict)
    # Asset kinds the tool takes only by EMBEDDING (see EmbeddedAsset). A kind may appear here
    # AND in `unsupported_assets`: it cannot be referenced, but it can be embedded.
    embedded_assets: dict[str, EmbeddedAsset] = field(default_factory=dict)
    # How a placed component carries the library part it is bound to (see PlacementBinding).
    placement_binding: PlacementBinding = PlacementBinding()

    def capturable_assets(self) -> tuple[str, ...]:
        """Kinds a CAPTURE session can fetch by reference, in registered order.

        An embeddable kind is excluded: the payload comes from a file the part already holds, so
        asking a vendor for a second, tool-specific copy would be busywork.
        """
        return tuple(k for k in self.asset_kinds if k not in self.unsupported_assets)

    def closable_assets(self) -> tuple[str, ...]:
        """Kinds a part can actually END UP holding, in registered order.

        This is what readiness reports on, and it is deliberately wider than
        `capturable_assets`: a kind that cannot be referenced but CAN be embedded is a real gap
        with a real action behind it, so hiding it would be dishonest.
        """
        return tuple(
            k
            for k in self.asset_kinds
            if k not in self.unsupported_assets or k in self.embedded_assets
        )


_KICAD = EdaTool(
    key="kicad",
    label="KiCad",
    ignore=(
        "*.kicad_prl",  # PROJECT-LOCAL per-user settings; KiCad's docs say do not commit
        "fp-info-cache",  # regenerated footprint cache, machine-specific and large
        "*.lck",  # editor lock files
        "*-backups/",  # KiCad's automatic backup archives
        "*.kicad_sch-bak",
        "*.kicad_pcb-bak",
        "_autosave-*",
        "*.000",  # legacy rescue/backup artifacts
    ),
    # KiCad's design sources are all s-expression TEXT and must stay diffable/mergeable.
    text=(
        "*.kicad_sch",
        "*.kicad_pcb",
        "*.kicad_sym",
        "*.kicad_mod",
        "*.kicad_pro",
        "*.kicad_wks",
        "*.kicad_dru",
        "*.net",
    ),
    binary=("*.wrl", "*.step", "*.stp"),
    # Stockroom edits .kicad_sch through the byte-preserving sexp layer, so a KiCad binding
    # lives in the schematic itself: written in the SAME transaction as the fill it records,
    # untouched by annotation, and carried to a peer by the project's own git.
    placement_binding=PlacementBinding(field="Stockroom ID", writable=True),
)

_ALTIUM = EdaTool(
    key="altium",
    label="Altium Designer",
    ignore=(
        "History/",  # Altium's local revision history folder
        "__Previews/",
        "Project Logs for*/",
        "Project Outputs for*/",
        "*.$$$",
        "*.PcbDoc.bak*",
        "*.SchDoc.bak*",
    ),
    # OLE2 compound documents: unmergeable, and a line-ending rewrite is unrecoverable.
    binary=(
        "*.PcbLib",
        "*.SchLib",
        "*.IntLib",
        "*.PcbDoc",
        "*.SchDoc",
        "*.PcbLib3D",
    ),
    # INI-style text -- the DbLib is emitted as deterministic INI by altium/dblib.py, so
    # marking it binary would destroy the diffability that makes review possible.
    text=("*.DbLib", "*.PrjPcb", "*.PrjScr", "*.OutJob"),
    # Altium takes a 3D model as a 3D Body object INSIDE the footprint's .PcbLib binary,
    # so no database/reference mechanism can carry it. Verified 2026-07-24; see the ledger
    # FINDINGS block. Generic readiness code reads this rather than special-casing Altium.
    unsupported_assets={
        "model": (
            "Altium stores 3D as a 3D Body inside the footprint's .PcbLib (an OLE2 "
            "binary), so it cannot be attached by reference; it must be embedded."
        )
    },
    # ... but it CAN be embedded, verified end to end 2026-07-25 (`stockroom.altium.embed3d`):
    # Altium itself is driven to write the 3D body into the footprint's own .PcbLib, and the result
    # is checked by reading the container back from OUTSIDE Altium. So the 3D gap is now REPORTED
    # and has a real action behind it, instead of being hidden as impossible.
    embedded_assets={
        "model": EmbeddedAsset(
            container="footprint",
            source="model",
            requires_tool_installed=True,
            reason=(
                "A 3D body is written into the footprint's .PcbLib by Altium itself, so "
                "embedding needs Altium installed on this machine."
            ),
        )
    },
    # A .SchDoc is an OLE2 binary Stockroom reads and never writes, so it cannot stamp a
    # binding onto an existing placement; the binding is kept on the project record instead.
    # A component placed from Stockroom's own DbLib still arrives carrying this parameter,
    # because Altium copies the DbLib column onto the placement itself.
    placement_binding=PlacementBinding(
        field="Stockroom ID",
        writable=False,
        reason=(
            "A .SchDoc is an OLE2 binary that Stockroom reads but never writes, so an "
            "assignment is recorded by Stockroom rather than stamped into the schematic."
        ),
    ),
)

# Declaration order is MEANINGFUL: it is the order tools are offered and reported in, and the
# first entry is the default target. KiCad leads because it is the library Stockroom itself
# writes. Do NOT sort this -- generated FILES are made deterministic by sorting at the point of
# emission (see `_resolve`), which is a separate concern from presentation order.
_REGISTRY: dict[str, EdaTool] = {t.key: t for t in (_KICAD, _ALTIUM)}


def all_tools() -> tuple[EdaTool, ...]:
    """Every registered tool, in declaration order (see `_REGISTRY`)."""
    return tuple(_REGISTRY.values())


def default_tool() -> EdaTool:
    """The tool the app targets when the user has not chosen one. Explicit rather than
    "whichever sorts first", which silently made Altium the default once."""
    return next(iter(_REGISTRY.values()))


def get_tool(key: str) -> EdaTool:
    """Look up a tool. Raises KeyError on an unknown key -- never falls back to a default,
    because a silent fallback to KiCad is exactly what produced the attach-clobber bug."""
    try:
        return _REGISTRY[key]
    except KeyError:
        known = ", ".join(sorted(_REGISTRY))
        raise KeyError(f"unknown EDA tool {key!r}; known tools: {known}") from None


def _resolve(keys, extra_tools) -> list[EdaTool]:
    """Registered tools for `keys`, plus any ad-hoc `extra_tools`, deduped and ordered by
    key so generated output is deterministic and never churns between runs."""
    tools = {get_tool(k).key: get_tool(k) for k in (keys or ())}
    for tool in extra_tools or ():
        tools[tool.key] = tool
    return [tools[k] for k in sorted(tools)]


def _dedupe(items) -> list[str]:
    """Preserve first-seen order while dropping duplicates, so two tools claiming the same
    pattern emit it once."""
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            out.append(item)
    return out


def workspace_gitignore(keys=(), *, extra_tools=()) -> str:
    """The `.gitignore` for a workspace holding files for `keys`.

    Only per-user and generated artifacts are listed. Design SOURCES are never ignored --
    ignoring them is how a peer ends up with a project that will not open.
    """
    tools = _resolve(keys, extra_tools)
    lines = [GENERATED_HEADER]
    for tool in tools:
        if not tool.ignore:
            continue
        lines.append(f"# {tool.label}: per-user and generated files (never design sources)")
        lines.extend(_dedupe(tool.ignore))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def workspace_gitattributes(keys=(), *, extra_tools=()) -> str:
    """The `.gitattributes` for a workspace holding files for `keys`.

    `binary` (= `-diff -merge -text`) both protects the bytes and makes git refuse to
    auto-merge a format that cannot be merged, which turns silent corruption into a
    conflict a human can actually resolve.
    """
    tools = _resolve(keys, extra_tools)
    lines = [GENERATED_HEADER]
    for tool in tools:
        if not (tool.binary or tool.text):
            continue
        lines.append(f"# {tool.label}")
        for pattern in _dedupe(tool.text):
            lines.append(f"{pattern} text eol=lf")
        for pattern in _dedupe(tool.binary):
            lines.append(f"{pattern} binary")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"
