/**
 * Committed UI-copy overrides, written by dev mode (Ctrl+Shift+D, then click any label). This
 * file is the SOURCE OF TRUTH for any label the owner has reworded: it is read on every render
 * for everyone (not a per-machine setting), so a saved rewording ships with the app. A key is a
 * stable copy id (see <Text id="...">); an absent id falls back to the default text written in
 * the JSX. Generated by POST /api/dev/save - safe to hand-edit.
 */
export const COPY_OVERRIDES: Record<string, string> = {};
