/**
 * The catalogue of stable dev-mode element ids: one row per meaningful area/element in the app. This is
 * the single source of truth for the ID system (mirroring lib/copy.tsx's id convention). Each element in
 * the app carries a `data-dev-id` whose value is one of these ids (dot-namespaced `area.element`,
 * lowercase-kebab per segment; the first segment is the area). Dev mode's inspect surface, the "Show IDs"
 * overlay, and the searchable catalogue all read this list, and later phases (per-element override, layout)
 * key their committed overrides on these same ids. Generated from the parallel-scout blueprint; keep it in
 * sync with the `data-dev-id` attributes in source (the parity test enforces it).
 */
export interface DevIdEntry {
  // The stable id, e.g. "component-browser.spec-sheet". Its first dot-segment is the area.
  id: string;
  // A short human label for the catalogue + the inspect badge.
  label: string;
  // The area (first id segment), for grouping the catalogue.
  area: string;
}

export const DEV_IDS: DevIdEntry[] = [
  { id: "rail.root", label: "Navigation rail", area: "rail" },
  { id: "rail.wordmark", label: "Wordmark tile", area: "rail" },
  { id: "rail.nav", label: "Primary nav group", area: "rail" },
  { id: "rail.nav-components", label: "Components nav item", area: "rail" },
  { id: "rail.nav-projects", label: "Projects nav item", area: "rail" },
  { id: "rail.nav-stm", label: "STM Viewer nav item", area: "rail" },
  { id: "rail.footer", label: "Rail footer", area: "rail" },
  { id: "rail.nav-settings", label: "Settings nav item", area: "rail" },
  { id: "rail.about", label: "About button", area: "rail" },
  { id: "rail.collapse", label: "Collapse rail toggle", area: "rail" },
  { id: "rail.utility", label: "Update + theme utility row", area: "rail" },
  { id: "rail.update", label: "Update / up-to-date control", area: "rail" },
  { id: "rail.theme-toggle", label: "Theme toggle", area: "rail" },
  { id: "about.root", label: "About dialog", area: "about" },
  { id: "onboarding.gate", label: "Onboarding gate", area: "onboarding" },
  { id: "toast.status", label: "Toast status", area: "toast" },
  { id: "capture.status", label: "Guided capture status", area: "capture" },
  { id: "about.scrim", label: "About backdrop", area: "about" },
  { id: "about.icon", label: "About logo tile", area: "about" },
  { id: "about.title", label: "About title", area: "about" },
  { id: "about.credit", label: "About credit line", area: "about" },
  { id: "about.stale", label: "About stale-frontend note", area: "about" },
  { id: "about.close", label: "Close About", area: "about" },
  { id: "about.links", label: "About social links", area: "about" },
  { id: "components.root", label: "Components page", area: "components" },
  { id: "components.picker", label: "Parts picker column", area: "components" },
  { id: "components.list-title", label: "Parts list title strip", area: "components" },
  { id: "components.add-parts", label: "Add Parts button", area: "components" },
  { id: "components.list-scroll", label: "Parts list scroll area", area: "components" },
  { id: "components.detail-pane", label: "Detail viewport column", area: "components" },
  { id: "components.empty", label: "Empty library state", area: "components" },
  { id: "components.list-loading", label: "Parts list loading state", area: "components" },
  { id: "components.list-failed", label: "Parts list failure state", area: "components" },
  { id: "components.list-unreachable", label: "Parts service unavailable state", area: "components" },
  { id: "stm.tabs", label: "STM sections", area: "stm" },
  { id: "stm.tab-explorer", label: "STM explorer tab", area: "stm" },
  { id: "stm.tab-compatibility", label: "STM compatibility tab", area: "stm" },
  { id: "components.list-no-match", label: "Parts list no-match state", area: "components" },
  { id: "components.select-prompt", label: "No-selection prompt", area: "components" },
  { id: "projects.root", label: "Projects page", area: "projects" },
  { id: "projects.picker", label: "Project picker column", area: "projects" },
  { id: "projects.list-title", label: "Project list title strip", area: "projects" },
  { id: "projects.workspace", label: "Selected project workspace", area: "projects" },
  { id: "projects.title-strip", label: "Project title strip", area: "projects" },
  { id: "projects.tabs", label: "Project tool tabs", area: "projects" },
  { id: "projects.tab-overview", label: "Overview tab", area: "projects" },
  { id: "projects.tab-bom", label: "BOM tab", area: "projects" },
  { id: "projects.tab-build", label: "Build tab", area: "projects" },
  { id: "projects.tab-activity", label: "Activity tab", area: "projects" },
  { id: "projects.overview", label: "Overview workbench", area: "projects" },
  { id: "projects.bom", label: "BOM workbench", area: "projects" },
  { id: "projects.build", label: "Build workbench", area: "projects" },
  { id: "projects.activity", label: "Activity workbench", area: "projects" },
  { id: "projects.placement-stage", label: "Placement map", area: "projects" },
  { id: "projects.board-control", label: "PCB board control", area: "projects" },
  { id: "projects.document-control", label: "Project document control", area: "projects" },
  { id: "projects.bom-filter-control", label: "BOM filter control", area: "projects" },
  { id: "projects.bom-line-control", label: "BOM line control", area: "projects" },
  { id: "projects.build-placement-control", label: "Build placement control", area: "projects" },
  { id: "projects.native-board-render", label: "Native PCB render", area: "projects" },
  { id: "projects.loading", label: "Projects loading state", area: "projects" },
  { id: "projects.empty", label: "Projects empty state", area: "projects" },
  { id: "projects.picker.loading", label: "Project picker loading state", area: "projects" },
  { id: "projects.picker.failed", label: "Project picker failure state", area: "projects" },
  { id: "projects.workspace.loading", label: "Project workspace loading state", area: "projects" },
  { id: "projects.workspace.error", label: "Project workspace failure state", area: "projects" },
  { id: "projects.runtime-missing", label: "Project native runtime missing state", area: "projects" },
  { id: "projects.placement-blocked", label: "Project placement blocked state", area: "projects" },
  { id: "projects.native-action-blocked", label: "Project native action preview guard", area: "projects" },
  { id: "projects.no-repository", label: "Project repository missing state", area: "projects" },
  { id: "projects.repository-diverged", label: "Project repository diverged state", area: "projects" },
  { id: "projects.shared-review", label: "Project shared review state", area: "projects" },
  { id: "projects.build-complete", label: "Project build complete state", area: "projects" },
  { id: "components.finder", label: "Search + facet finder", area: "components" },
  { id: "components.search-box", label: "Search box", area: "components" },
  { id: "components.search-input", label: "Search input", area: "components" },
  { id: "components.advanced-search", label: "Advanced parametric search", area: "components" },
  { id: "components.filter-button", label: "Filters button", area: "components" },
  { id: "components.filter-summary", label: "Active filter summary", area: "components" },
  { id: "components.filter-panel", label: "Filters popover", area: "components" },
  { id: "components.filter-complete", label: "Complete-only toggle", area: "components" },
  { id: "components.filter-duplicates", label: "Duplicates toggle", area: "components" },
  { id: "components.filter-categories", label: "Category facet list", area: "components" },
  { id: "components.list", label: "Grouped parts list", area: "components" },
  { id: "components.category-header", label: "Category group header", area: "components" },
  { id: "components.row", label: "Part row", area: "components" },
  { id: "components.row-thumbnail", label: "Row thumbnail tile", area: "components" },
  // The row's one visually primary item, and the metadata that must yield to it. Addressable
  // because "did the identifier keep its space" is a question about these two boxes and nothing
  // else, and it was previously unanswerable without reasoning about flex maths.
  { id: "components.row-mpn", label: "Row part number", area: "components" },
  { id: "components.row-package", label: "Row package label", area: "components" },
  { id: "components.row-duplicate", label: "Duplicate badge", area: "components" },
  { id: "components.row-warn", label: "Incomplete warning icon", area: "components" },
  // The opened component. Per-COMPONENT ids are dynamic (`component-browser.component[<id>]`,
  // its `.tab`, `.representation[<kind>]`, and `.provider[<provider id>]`), built by
  // lib/componentDevIds.ts, so they carry no catalogue row: the set is the library and the
  // provider registry, not a fixed list.
  { id: "component-browser.root", label: "Opened component workspace", area: "component-browser" },
  { id: "component-browser.columns", label: "Three-column workspace band", area: "component-browser" },
  { id: "component-browser.column-splitter", label: "Column splitter handle", area: "component-browser" },
  { id: "component-browser.column-cad", label: "CAD Assets column", area: "component-browser" },
  { id: "component-browser.column-specifications", label: "Specifications column", area: "component-browser" },
  { id: "component-browser.column-sourcing", label: "Sourcing and Resources column", area: "component-browser" },
  { id: "component-browser.header-mpn", label: "Canonical part number", area: "component-browser" },
  { id: "component-browser.header-lifecycle", label: "Lifecycle state", area: "component-browser" },
  { id: "component-browser.header-description", label: "Manufacturer and description line", area: "component-browser" },
  { id: "component-browser.header-classification", label: "Category, package and pin count line", area: "component-browser" },
  { id: "component-browser.header-key-facts", label: "Key facts line", area: "component-browser" },
  { id: "component-browser.header-actions", label: "Identity action group", area: "component-browser" },
  { id: "component-browser.header-manufacturer-page", label: "Manufacturer Page action", area: "component-browser" },
  { id: "component-browser.datasheet-missing", label: "Datasheet Missing state", area: "component-browser" },
  { id: "component-browser.datasheet-find", label: "Find Datasheet action", area: "component-browser" },
  { id: "component-browser.datasheet-more", label: "Datasheet split-button menu trigger", area: "component-browser" },
  { id: "component-browser.datasheet-menu", label: "Datasheet menu surface", area: "component-browser" },
  { id: "component-browser.datasheet-current", label: "Current Datasheet menu item", area: "component-browser" },
  { id: "component-browser.datasheet-revision", label: "One superseded datasheet revision", area: "component-browser" },
  { id: "component-browser.datasheet-other", label: "One other document in the datasheet menu", area: "component-browser" },
  { id: "component-browser.copy-mpn", label: "Copy MPN action", area: "component-browser" },
  { id: "component-browser.manage", label: "Manage menu trigger", area: "component-browser" },
  { id: "component-browser.manage-menu", label: "Manage menu surface", area: "component-browser" },
  { id: "component-browser.manage-item", label: "One Manage menu item", area: "component-browser" },
  { id: "component-browser.export-format", label: "One export format action", area: "component-browser" },
  { id: "component-browser.open-in-application", label: "One installed EDA application", area: "component-browser" },
  { id: "component-browser.quality-summary", label: "Data quality summary", area: "component-browser" },
  { id: "component-browser.quality-segment", label: "One quality summary segment", area: "component-browser" },
  { id: "component-browser.cad-asset", label: "Every CAD asset module", area: "component-browser" },
  { id: "component-browser.asset-header", label: "CAD asset expand control", area: "component-browser" },
  { id: "component-browser.asset-preview", label: "CAD asset preview stage", area: "component-browser" },
  { id: "component-browser.asset-evidence", label: "CAD asset evidence line", area: "component-browser" },
  { id: "component-browser.preferred-source", label: "Preferred CAD source", area: "component-browser" },
  { id: "component-browser.asset-issue", label: "CAD asset issue line", area: "component-browser" },
  { id: "component-browser.asset-maximize", label: "Open the full CAD preview", area: "component-browser" },
  { id: "component-browser.show-all-assets", label: "Show all three CAD modules", area: "component-browser" },
  { id: "component-browser.cad-source-confirm", label: "What changing the CAD source replaces", area: "component-browser" },
  { id: "component-browser.symbol-canvas", label: "Symbol drawing canvas", area: "component-browser" },
  { id: "component-browser.footprint-canvas", label: "Land pattern drawing canvas", area: "component-browser" },
  // The symbol drawing's three visibility switches and the land pattern's nine, plus its ruler.
  // Each is a real layer of the file being drawn, so each is separately addressable: a single
  // "layers" id would make every switch the same element to an override and to a screenshot.
  { id: "component-browser.asset-layer-pin-name", label: "Pin names visibility", area: "component-browser" },
  { id: "component-browser.asset-layer-pin-number", label: "Pin numbers visibility", area: "component-browser" },
  { id: "component-browser.asset-layer-electrical", label: "Electrical type visibility", area: "component-browser" },
  { id: "component-browser.asset-layer-copper", label: "Copper visibility", area: "component-browser" },
  { id: "component-browser.asset-layer-mask", label: "Solder mask visibility", area: "component-browser" },
  { id: "component-browser.asset-layer-paste", label: "Paste visibility", area: "component-browser" },
  { id: "component-browser.asset-layer-silkscreen", label: "Silkscreen visibility", area: "component-browser" },
  { id: "component-browser.asset-layer-fabrication", label: "Fabrication visibility", area: "component-browser" },
  { id: "component-browser.asset-layer-courtyard", label: "Courtyard visibility", area: "component-browser" },
  { id: "component-browser.asset-layer-numbers", label: "Pad numbers visibility", area: "component-browser" },
  { id: "component-browser.asset-layer-origin", label: "Footprint origin visibility", area: "component-browser" },
  { id: "component-browser.asset-layer-dimensions", label: "Overall dimensions visibility", area: "component-browser" },
  { id: "component-browser.asset-measure", label: "Measure on the land pattern", area: "component-browser" },
  { id: "component-browser.asset-control-strip", label: "One preview's control strip", area: "component-browser" },
  { id: "component-browser.asset-options-symbol", label: "Symbol visibility button", area: "component-browser" },
  { id: "component-browser.asset-options-footprint", label: "Land pattern visibility button", area: "component-browser" },
  { id: "component-browser.asset-options-panel", label: "A preview's visibility panel", area: "component-browser" },
  { id: "component-browser.spec-conflict-marker", label: "A disagreeing value's marker", area: "component-browser" },
  { id: "component-browser.spec-filter", label: "One specification filter", area: "component-browser" },
  { id: "component-browser.spec-group-toggle", label: "Specification group disclosure", area: "component-browser" },
  { id: "component-browser.pinout-open", label: "View Pinout action", area: "component-browser" },
  { id: "component-browser.lifecycle", label: "Lifecycle and availability region", area: "component-browser" },
  { id: "component-browser.manufacturer-status", label: "The manufacturer's own product status", area: "component-browser" },
  { id: "component-browser.offers", label: "Distributor offers region", area: "component-browser" },
  { id: "component-browser.offers-table", label: "The dense distributor offers table", area: "component-browser" },
  { id: "component-browser.pricing", label: "Pricing and lead time region", area: "component-browser" },
  { id: "component-browser.total-stock", label: "Total stock across every offer", area: "component-browser" },
  { id: "component-browser.offer-failures", label: "Sources that could not be refreshed", area: "component-browser" },
  { id: "component-browser.offer-row", label: "One distributor offer row", area: "component-browser" },
  { id: "component-browser.offer-listing", label: "Open one distributor listing", area: "component-browser" },
  { id: "component-browser.offers-all", label: "View Price Breaks action", area: "component-browser" },
  { id: "component-browser.refresh-offers", label: "Refresh Offers action", area: "component-browser" },
  { id: "component-browser.documents", label: "Documents region", area: "component-browser" },
  { id: "component-browser.preferred-datasheet-reason", label: "Why this datasheet copy was chosen", area: "component-browser" },
  { id: "component-browser.document-row", label: "One document row", area: "component-browser" },
  { id: "component-browser.document-open", label: "Open one document", area: "component-browser" },
  { id: "component-browser.related", label: "Related parts region", area: "component-browser" },
  { id: "component-browser.related-row", label: "One related part", area: "component-browser" },
  { id: "component-browser.related-evidence", label: "The differences a relation was read off", area: "component-browser" },
  { id: "component-browser.related-not-validated", label: "Stockroom has not checked equivalence", area: "component-browser" },
  { id: "component-browser.provenance", label: "Data provenance and history region", area: "component-browser" },
  { id: "component-browser.compatibility-notice", label: "What a newer build's data means here", area: "component-browser" },
  { id: "component-browser.compatibility-view", label: "Name the read-only fields", area: "component-browser" },
  { id: "component-browser.compatibility-field", label: "One field this build cannot edit", area: "component-browser" },
  { id: "component-browser.provenance-sources", label: "Data Sources table", area: "component-browser" },
  { id: "component-browser.provenance-conflicts", label: "Field Conflicts region", area: "component-browser" },
  { id: "component-browser.conflict-row", label: "One field the sources disagree about", area: "component-browser" },
  { id: "component-browser.provenance-overrides", label: "Manual Overrides region", area: "component-browser" },
  { id: "component-browser.override-row", label: "One reviewed decision in force", area: "component-browser" },
  { id: "component-browser.provenance-intake", label: "Import and enrichment history", area: "component-browser" },
  { id: "component-browser.provenance-revisions", label: "Revision history", area: "component-browser" },
  { id: "component-browser.history-event", label: "One dated event in a history", area: "component-browser" },
  { id: "component-browser.provenance-diagnostics", label: "Technical diagnostics, developer mode only", area: "component-browser" },
  { id: "component-browser.provenance-nothing", label: "The silent provenance questions, in one line", area: "component-browser" },
  { id: "component-browser.provenance-all", label: "View Data Provenance action", area: "component-browser" },
  { id: "component-browser.empty-sections", label: "Reveal the empty sourcing sections", area: "component-browser" },
  { id: "component-browser.status-bar", label: "Opened component status bar", area: "component-browser" },
  { id: "component-browser.empty", label: "No component open", area: "component-browser" },
  { id: "component-browser.message", label: "Workspace loading / failure message", area: "component-browser" },
  { id: "component-browser.header", label: "Persistent identity header", area: "component-browser" },
  { id: "component-browser.header-datasheet", label: "Datasheet action", area: "component-browser" },
  { id: "component-browser.key-specs", label: "Main Specifications region", area: "component-browser" },
  { id: "component-browser.view-all", label: "View All action", area: "component-browser" },
  { id: "component-browser.pinout", label: "Pinout region", area: "component-browser" },
  { id: "component-browser.modal", label: "Component workspace modal", area: "component-browser" },
  { id: "component-browser.modal-close", label: "Close the workspace modal", area: "component-browser" },
  { id: "component-browser.datasheet-viewer", label: "Datasheet viewer window", area: "component-browser" },
  { id: "component-browser.datasheet-viewer-close", label: "Close the datasheet viewer", area: "component-browser" },
  { id: "component-browser.datasheet-pdf", label: "Datasheet PDF stage", area: "component-browser" },
  { id: "component-browser.datasheet-toolbar", label: "Datasheet viewer toolbar", area: "component-browser" },
  { id: "component-browser.datasheet-outline", label: "Datasheet table of contents", area: "component-browser" },
  { id: "component-browser.datasheet-page-number", label: "Current datasheet page", area: "component-browser" },
  { id: "component-browser.datasheet-previous", label: "Previous datasheet page", area: "component-browser" },
  { id: "component-browser.datasheet-next", label: "Next datasheet page", area: "component-browser" },
  { id: "component-browser.datasheet-zoom", label: "Datasheet zoom level", area: "component-browser" },
  { id: "component-browser.datasheet-zoom-in", label: "Zoom the datasheet in", area: "component-browser" },
  { id: "component-browser.datasheet-zoom-out", label: "Zoom the datasheet out", area: "component-browser" },
  { id: "component-browser.datasheet-rotate", label: "Rotate the datasheet", area: "component-browser" },
  { id: "component-browser.datasheet-open-external", label: "Open the datasheet outside Stockroom", area: "component-browser" },
  { id: "component-browser.datasheet-page-resource", label: "HTML datasheet page notice", area: "component-browser" },
  { id: "component-browser.datasheet-open-page", label: "Open an HTML datasheet page", area: "component-browser" },
  { id: "component-browser.datasheet-unavailable", label: "Document cannot be opened", area: "component-browser" },
  { id: "component-browser.datasheet-failed", label: "Datasheet load failure", area: "component-browser" },
  { id: "component-browser.datasheet-failure-reason", label: "What failed when the datasheet did not open", area: "component-browser" },
  { id: "component-browser.datasheet-retry", label: "Retry loading the datasheet", area: "component-browser" },
  { id: "component-browser.datasheet-open-source", label: "Open the datasheet's source page", area: "component-browser" },
  // The exhaustive sheets the compact tabs hand off to. Everything below lives INSIDE the one
  // workspace modal, which is the only surface in the opened component allowed to scroll.
  { id: "component-browser.spec-search", label: "Search specifications", area: "component-browser" },
  { id: "component-browser.spec-group", label: "One specification group", area: "component-browser" },
  { id: "component-browser.spec-row", label: "One specification row", area: "component-browser" },
  { id: "component-browser.spec-value", label: "One specification's value in force", area: "component-browser" },
  { id: "component-browser.spec-source", label: "The source a specification's value came from", area: "component-browser" },
  { id: "component-browser.spec-constraint", label: "A category constraint this value fails", area: "component-browser" },
  { id: "component-browser.spec-evidence-toggle", label: "Open a specification's source evidence", area: "component-browser" },
  { id: "component-browser.spec-provenance", label: "One specification's attached provenance", area: "component-browser" },
  { id: "component-browser.spec-override-replaced", label: "What a reviewed override replaced", area: "component-browser" },
  { id: "component-browser.spec-pin-state", label: "Whether a pinned source is in force", area: "component-browser" },
  { id: "component-browser.spec-alternates", label: "The other values offered for a specification", area: "component-browser" },
  { id: "component-browser.spec-alternate", label: "An alternate value for a specification", area: "component-browser" },
  { id: "component-browser.spec-use-alternate", label: "Put one source's value in force", area: "component-browser" },
  { id: "component-browser.spec-view-source", label: "Open the source behind one value", area: "component-browser" },
  { id: "component-browser.spec-add-override", label: "Record a reviewed override", area: "component-browser" },
  { id: "component-browser.spec-clear-override", label: "Withdraw a reviewed override", area: "component-browser" },
  { id: "component-browser.spec-clear-preferred-source", label: "Go back to the ranked source", area: "component-browser" },
  { id: "component-browser.spec-anchors", label: "Specification section anchor strip", area: "component-browser" },
  { id: "component-browser.spec-anchor", label: "One specification section anchor", area: "component-browser" },
  { id: "component-browser.spec-editor", label: "The attached specification editor", area: "component-browser" },
  { id: "component-browser.spec-override-input", label: "Override value editor", area: "component-browser" },
  { id: "component-browser.spec-editor-unit", label: "The unit a reviewed value is in", area: "component-browser" },
  { id: "component-browser.spec-editor-type", label: "The kind of value being entered", area: "component-browser" },
  { id: "component-browser.spec-editor-source", label: "Whose answer this field takes", area: "component-browser" },
  { id: "component-browser.spec-editor-verification", label: "Whether a reviewed value is confirmed", area: "component-browser" },
  { id: "component-browser.spec-editor-reason", label: "Why a reviewed value was recorded", area: "component-browser" },
  { id: "component-browser.spec-editor-prefer", label: "Whether a reviewed value outranks the sources", area: "component-browser" },
  { id: "component-browser.spec-editor-error", label: "Why a specification edit cannot be saved", area: "component-browser" },
  { id: "component-browser.spec-override-save", label: "Save an override", area: "component-browser" },
  { id: "component-browser.spec-override-cancel", label: "Cancel an override", area: "component-browser" },
  { id: "component-browser.spec-write-failed", label: "A specification write that did not save", area: "component-browser" },
  { id: "component-browser.pinout-table", label: "Complete pinout table", area: "component-browser" },
  { id: "component-browser.pinout-filter", label: "Filter the pinout table", area: "component-browser" },
  { id: "component-browser.pinout-lookup", label: "Look up a pinout", area: "component-browser" },
  { id: "component-browser.pinout-apply", label: "Apply Pinout action", area: "component-browser" },
  { id: "component-browser.sourcing-sheet", label: "Full sourcing sheet", area: "component-browser" },
  { id: "component-browser.source-state", label: "One source's outcome", area: "component-browser" },
  { id: "component-browser.offer", label: "One distributor offer", area: "component-browser" },
  { id: "component-browser.offer-ladder", label: "One offer's price ladder", area: "component-browser" },
  { id: "component-browser.relationship-item", label: "One suggested related part", area: "component-browser" },
  { id: "component-browser.resource-link", label: "One provider document link", area: "component-browser" },
  { id: "component-browser.sources-sheet", label: "Full sources and history sheet", area: "component-browser" },
  { id: "component-browser.sources.tabs", label: "Sources and history tab bar", area: "component-browser" },
  { id: "component-browser.sources.tab-fields", label: "Field Sources tab", area: "component-browser" },
  { id: "component-browser.sources.tab-records", label: "Source Records tab", area: "component-browser" },
  { id: "component-browser.sources.tab-changes", label: "Changes tab", area: "component-browser" },
  { id: "component-browser.sources.tab-diagnostics", label: "Diagnostics tab", area: "component-browser" },
  { id: "component-browser.field-source-row", label: "One attributed field", area: "component-browser" },
  { id: "component-browser.field-source-apply", label: "Put an alternate value in force", area: "component-browser" },
  { id: "component-browser.source-record-row", label: "One captured source record", area: "component-browser" },
  { id: "component-browser.source-refresh", label: "Refresh Sourcing action", area: "component-browser" },
  { id: "component-browser.enrich", label: "Source lookup panel", area: "component-browser" },
  { id: "component-browser.change-entry", label: "One commit in the component timeline", area: "component-browser" },
  { id: "component-browser.change-diff", label: "Open the visual diff for one commit", area: "component-browser" },
  { id: "component-browser.diagnostics-toggle", label: "Show or hide diagnostics", area: "component-browser" },
  { id: "component-browser.diagnostics-raw", label: "Show or hide the canonical record", area: "component-browser" },
  // Manage Models: one component-scoped provider list, modal browser, and status strip.
  { id: "component-browser.manage-models", label: "Manage Models workspace", area: "component-browser" },
  { id: "component-browser.cad-tab-models", label: "Models tab", area: "component-browser" },
  { id: "component-browser.cad-tab-manage-models", label: "Manage Models tab", area: "component-browser" },
  { id: "component-browser.provider-list", label: "CAD provider list", area: "component-browser" },
  // The SHARED role every provider row declares (`data-dev-role`). Each row also carries its own
  // per-provider instance id, so one row can be tuned without touching the others; this row is what
  // an edit meant for ALL of them is keyed on.
  { id: "component-browser.provider-row", label: "Every provider coverage row", area: "component-browser" },
  { id: "component-browser.provider-open", label: "Open one provider", area: "component-browser" },
  { id: "component-browser.provider-import", label: "Import downloaded files", area: "component-browser" },
  { id: "component-browser.eda-selection", label: "EDA selection", area: "component-browser" },
  { id: "component-browser.provider-back", label: "Provider browser Back", area: "component-browser" },
  { id: "component-browser.provider-forward", label: "Provider browser Forward", area: "component-browser" },
  { id: "component-browser.provider-reload", label: "Provider browser Reload", area: "component-browser" },
  { id: "component-browser.provider-dialog", label: "Provider browser modal", area: "component-browser" },
  { id: "component-browser.provider-dialog-titlebar", label: "Provider browser modal title bar", area: "component-browser" },
  { id: "component-browser.provider-close", label: "Close provider browser", area: "component-browser" },
  { id: "component-browser.provider-viewport", label: "Embedded provider page", area: "component-browser" },
  { id: "component-browser.provider-status", label: "Model download status", area: "component-browser" },
  { id: "component-browser.identity-sheet", label: "Identity editing sheet", area: "component-browser" },
  { id: "component-browser.identity-field", label: "One editable identity field", area: "component-browser" },
  // The category MOVE control is `detail.category-control` now: the identity sheet's hand-written
  // select was a second editor for a field the generated EDA registry already owns, so the sheet
  // renders the handoff band instead and the band's AdaptiveChoice is the one control.
  // The EDA handoff block (components/HandoffBand.tsx). Per-field cell ids are DERIVED
  // (`detail.handoff-<field key>`) from the generated EDA registry, so a new registry field brings
  // its own cell id and this catalogue needs no edit.
  { id: "detail.handoff", label: "EDA handoff block", area: "detail" },
  // The SHARED roles the per-field cells declare. Each cell also carries its own
  // `detail.handoff-field[<field key>]` instance id, built by lib/componentDevIds.ts, so one
  // field can be tuned alone and a registry field key can never forge another cell's id.
  { id: "detail.handoff-field", label: "Every handoff field cell", area: "detail" },
  { id: "detail.handoff-open", label: "Every handoff open link", area: "detail" },
  { id: "detail.category-control", label: "Category selector", area: "detail" },
  { id: "detail.handoff-ready", label: "Handoff readiness count", area: "detail" },
  // The 3D model instrument (components/Glb3DView.tsx + lib/threeScene.ts).
  { id: "detail.model-spin", label: "3D idle-spin toggle", area: "detail" },
  { id: "detail.model-settings", label: "3D model settings toggle", area: "detail" },
  { id: "detail.model-settings-popover", label: "3D model settings panel", area: "detail" },
  { id: "detail.model-views", label: "3D canonical view switcher", area: "detail" },
  { id: "detail.model-board", label: "3D land-pattern (footprint) toggle", area: "detail" },
  { id: "detail.model-layers", label: "3D layer + shading bar", area: "detail" },
  { id: "detail.model-shading", label: "3D shading mode group", area: "detail" },
  { id: "detail.model-show-model", label: "3D layer: model", area: "detail" },
  { id: "detail.model-show-board", label: "3D layer: PCB substrate", area: "detail" },
  { id: "detail.model-shade-realistic", label: "3D shading: realistic", area: "detail" },
  { id: "detail.model-shade-studio", label: "3D shading: studio", area: "detail" },
  { id: "detail.model-shade-xray", label: "3D shading: x-ray", area: "detail" },
  { id: "detail.model-view-iso", label: "3D view: three-quarter", area: "detail" },
  { id: "detail.model-view-top", label: "3D view: top down", area: "detail" },
  { id: "detail.model-view-front", label: "3D view: front elevation", area: "detail" },
  // `detail.pinout` / `detail.pinout-list` went with components/PinoutViewer.tsx. It had lost its
  // only importer when DetailPanel was deleted, and the workspace's own `PinoutTable` already
  // renders every column the record wrote (that one showed pin and name only). Its one remaining
  // capability, finding a signal in a large package, is `component-browser.pinout-filter`.
  { id: "search.root", label: "Search overlay", area: "search" },
  { id: "search.query", label: "Query field", area: "search" },
  { id: "search.query-input", label: "Query input", area: "search" },
  { id: "search.close", label: "Close button", area: "search" },
  { id: "search.subbar", label: "Results + chips + sort bar", area: "search" },
  { id: "search.result-count", label: "Result count", area: "search" },
  { id: "search.chips", label: "Active filter chips", area: "search" },
  { id: "search.sort", label: "Sort control", area: "search" },
  { id: "search.rail", label: "Facet rail", area: "search" },
  { id: "search.rail-category", label: "Category facet group", area: "search" },
  { id: "search.rail-facet", label: "Generated spec facet group", area: "search" },
  { id: "search.single-value-facet", label: "Single-value facet", area: "search" },
  { id: "search.rail-instock", label: "In Stock toggle", area: "search" },
  { id: "search.results", label: "Results table container", area: "search" },
  { id: "search.results-table", label: "Results table", area: "search" },
  { id: "search.results-row", label: "Result row", area: "search" },
  { id: "search.footer", label: "Keyboard-hints footer", area: "search" },
  { id: "addpart.root", label: "Add-a-Part dialog", area: "addpart" },
  { id: "addpart.scrim", label: "Add-a-Part backdrop", area: "addpart" },
  { id: "addpart.header", label: "Add-a-Part header", area: "addpart" },
  { id: "addpart.close", label: "Add-a-Part close", area: "addpart" },
  { id: "addpart.body", label: "Add-a-Part body", area: "addpart" },
  { id: "ingest.root", label: "Add-a-Part flow", area: "ingest" },
  { id: "ingest.hero", label: "Lookup hero", area: "ingest" },
  { id: "ingest.input", label: "Link / part-number input", area: "ingest" },
  { id: "ingest.kind-control", label: "Passive kind control", area: "ingest" },
  { id: "ingest.package-control", label: "Passive package control", area: "ingest" },
  { id: "ingest.lookup", label: "Look Up button", area: "ingest" },
  { id: "ingest.stages", label: "Enrichment stages", area: "ingest" },
  { id: "ingest.path", label: "Part path strip", area: "ingest" },
  { id: "ingest.passive", label: "Passive add card", area: "ingest" },
  { id: "ingest.blocked", label: "Blocked-fetch card", area: "ingest" },
  { id: "ingest.nonpassive", label: "Needs-files card", area: "ingest" },
  { id: "ingest.pulled-summary", label: "Pulled summary", area: "ingest" },
  { id: "ingest.pulled-photo", label: "Pulled photo trigger", area: "ingest" },
  { id: "ingest.pulled-specs", label: "Pulled specs table", area: "ingest" },
  { id: "ingest.staged", label: "Review and Add list", area: "ingest" },
  { id: "ingest.candidate", label: "Staged candidate card", area: "ingest" },
  { id: "ingest.footprint-control", label: "Candidate footprint control", area: "ingest" },
  { id: "ingest.candidate-add", label: "Candidate Add to Components action", area: "ingest" },
  { id: "ingest.candidate-photo", label: "Candidate photo trigger", area: "ingest" },
  { id: "ingest.candidate-conflicts", label: "Candidate spec conflicts", area: "ingest" },
  { id: "ingest.passive-add", label: "Passive Add to Components action", area: "ingest" },
  { id: "ingest.bulk", label: "Import A List panel", area: "ingest" },
  { id: "ingest.bulk-input", label: "Bulk part-number paste well", area: "ingest" },
  { id: "ingest.bulk-import", label: "Bulk import action", area: "ingest" },
  { id: "ingest.bulk-preview", label: "Bulk import dry run", area: "ingest" },
  { id: "ingest.bulk-progress", label: "Bulk import progress line", area: "ingest" },
  { id: "ingest.bulk-error", label: "Bulk import failure", area: "ingest" },
  { id: "ingest.bulk-result", label: "Bulk import report", area: "ingest" },
  { id: "ingest.bulk-toggle", label: "Bulk report row filter", area: "ingest" },
  { id: "stm.root", label: "STM Viewer page", area: "stm" },
  { id: "stm.pinout", label: "Single-MCU pinout workspace", area: "stm" },
  { id: "stm.bench", label: "Universal support workbench", area: "stm" },
  { id: "stm.target-set-control", label: "Target set control", area: "stm" },
  // Shared roles for the two repeated STM pickers. Each button also carries its own
  // `stm.package[<name>]` / `stm.family[<family>]` instance id.
  { id: "stm.package", label: "Every package choice", area: "stm" },
  { id: "stm.family", label: "Every family choice", area: "stm" },
  { id: "stm.target-definition", label: "Target definition workspace", area: "stm" },
  { id: "stm.target-policy", label: "Target definition rules", area: "stm" },
  { id: "stm.socket-solution", label: "Socket solution workspace", area: "stm" },
  { id: "stm.target-map", label: "Physical package map", area: "stm" },
  { id: "stm.target-legend", label: "Interactive map legend", area: "stm" },
  { id: "stm.target-legend-guide", label: "Complete legend guide", area: "stm" },
  { id: "stm.target-inspector", label: "Physical position inspector", area: "stm" },
  { id: "stm.lens.compatibility", label: "Compatibility map lens", area: "stm" },
  { id: "stm.lens.foundation", label: "Run-critical map lens", area: "stm" },
  { id: "stm.lens.electrical", label: "Electrical-role map lens", area: "stm" },
  { id: "stm.lens.access", label: "Service-access map lens", area: "stm" },
  { id: "stm.lens.board", label: "Routing-plan map lens", area: "stm" },
  { id: "stm.inspector.decision", label: "Position decision view", area: "stm" },
  { id: "stm.inspector.targets", label: "Position MCU view", area: "stm" },
  { id: "stm.inspector.evidence", label: "Position evidence view", area: "stm" },
  { id: "settings.root", label: "Settings page", area: "settings" },
  { id: "settings.title", label: "Settings heading", area: "settings" },
  { id: "settings.machine-band", label: "Application delivery and machine readiness", area: "settings" },
  { id: "settings.nav", label: "Settings group nav", area: "settings" },
  { id: "settings.nav-general", label: "General settings group", area: "settings" },
  { id: "settings.nav-library", label: "Library group", area: "settings" },
  { id: "settings.nav-eda", label: "EDA Tools group", area: "settings" },
  { id: "settings.nav-maintenance", label: "Maintenance group", area: "settings" },
  { id: "settings.nav-sources", label: "Data Sources group", area: "settings" },
  { id: "settings.content", label: "Active settings group content", area: "settings" },
  { id: "settings.altium", label: "Altium Database Library section", area: "settings" },
  { id: "settings.cubemx", label: "STM32CubeMX Data section", area: "settings" },
  { id: "settings.appearance", label: "Appearance section", area: "settings" },
  { id: "settings.appearance-theme", label: "Theme toggle", area: "settings" },
  { id: "settings.appearance-reset-applied", label: "Reset applied design", area: "settings" },
  { id: "settings.profiles", label: "Component Profiles section", area: "settings" },
  { id: "settings.profiles-row", label: "Profile row", area: "settings" },
  { id: "settings.profiles-create", label: "Create profile row", area: "settings" },
  { id: "settings.sync", label: "Component Sync section", area: "settings" },
  { id: "settings.sync-action", label: "Pull And Push Library button", area: "settings" },
  { id: "settings.github", label: "GitHub section", area: "settings" },
  { id: "settings.github-token", label: "GitHub token input", area: "settings" },
  { id: "settings.kicad", label: "KiCad section", area: "settings" },
  { id: "settings.kicad-wire", label: "Recheck And Wire KiCad button", area: "settings" },
  { id: "settings.kicad-overrides", label: "KiCad override inputs", area: "settings" },
  { id: "settings.librarysync", label: "Library Sync settings group", area: "settings" },
  { id: "settings.library-lfs", label: "Where the library stores binary payloads", area: "settings" },
  { id: "settings.library-lfs.adopt", label: "Store the library binaries in Git LFS", area: "settings" },
  { id: "settings.library-hygiene", label: "Files the library shares that it should not", area: "settings" },
  { id: "settings.library-hygiene.sync", label: "Stop sharing the library per-user files", area: "settings" },
  { id: "settings.completion", label: "Library Completion section", area: "settings" },
  { id: "settings.completion-worklist", label: "What still needs a person", area: "settings" },
  { id: "settings.completion-worklist-row", label: "One provider trip for one component", area: "settings" },
  { id: "settings.completion-worklist-start", label: "Start this provider capture for this component", area: "settings" },
  { id: "settings.completion-worklist-run", label: "Work through every listed component in order", area: "settings" },
  { id: "settings.derivation", label: "Presentation Data section", area: "settings" },
  { id: "settings.cad-clear", label: "Clear CAD Files section", area: "settings" },
  { id: "settings.cad-clear.run", label: "Remove All CAD Files button", area: "settings" },
  { id: "settings.derivation.rebuild", label: "Recompute Presentation Data button", area: "settings" },
  { id: "settings.health", label: "Library Health section", area: "settings" },
  { id: "settings.health-repair", label: "Commit Safe Catalog Repairs button", area: "settings" },
  { id: "settings.rescan", label: "Procurement Rescan section", area: "settings" },
  { id: "settings.rescan-action", label: "Refresh Prices button", area: "settings" },
  { id: "settings.distributor", label: "Distributor APIs section", area: "settings" },
  { id: "settings.distributor-key", label: "Mouser key input", area: "settings" },
  { id: "settings.vendor-login-row", label: "API credential row", area: "settings" },
  { id: "settings.update", label: "Automatic Updates section", area: "settings" },
  { id: "altiumdb.section-progress", label: "DbLib ready meter", area: "altiumdb" },
  { id: "altiumdb.section-path", label: "DbLib install path row", area: "altiumdb" },
  { id: "altiumdb.section-odbc", label: "ODBC driver status + download", area: "altiumdb" },
  { id: "altiumdb.section-actions", label: "Regenerate / View Library", area: "altiumdb" },
  { id: "altiumdb.modal", label: "Altium DbLib modal", area: "altiumdb" },
  { id: "altiumdb.modal-filter", label: "DbLib filter control", area: "altiumdb" },
  { id: "altiumdb.modal-table", label: "DbLib parts table", area: "altiumdb" },
  { id: "altiumdb.setup-modal", label: "Altium setup guide modal", area: "altiumdb" },
  { id: "altiumdb.embed-all", label: "Embed every pending 3D model in one run", area: "altiumdb" },
  { id: "complete.root", label: "Complete Part dialog", area: "complete" },
  { id: "complete.header", label: "Complete Part header", area: "complete" },
  { id: "complete.cad", label: "CAD Files capture block", area: "complete" },
  { id: "complete.cad-checklist", label: "CAD capture checklist", area: "complete" },
  { id: "complete.cad-actions", label: "Get CAD Files buttons", area: "complete" },
  { id: "complete.cad-provider-outcomes", label: "CAD provider results", area: "complete" },
  { id: "complete.cad-live-status", label: "CAD capture live status", area: "complete" },
  { id: "complete.requirements", label: "Requirements list", area: "complete" },
  { id: "complete.requirement-row", label: "Requirement row", area: "complete" },
  { id: "complete.done", label: "Done button", area: "complete" },
  { id: "preview.root", label: "Preview dialog", area: "preview" },
  { id: "preview.header", label: "Preview header", area: "preview" },
  { id: "preview.close", label: "Preview close", area: "preview" },
  { id: "preview.stage", label: "Preview viewport", area: "preview" },
  { id: "detail.model-gizmo", label: "3D view cube", area: "detail" },
  { id: "preview.photo", label: "Product photo dialog", area: "preview" },
  { id: "preview.photo-count", label: "Photo carousel counter", area: "preview" },
  { id: "preview.photo-prev", label: "Photo carousel previous", area: "preview" },
  { id: "preview.photo-next", label: "Photo carousel next", area: "preview" },
  { id: "diff.root", label: "Diff dialog", area: "diff" },
  { id: "diff.header", label: "Diff header", area: "diff" },
  { id: "diff.tabs", label: "Diff type tabs", area: "diff" },
  { id: "diff.tab-symbol", label: "Symbol diff tab", area: "diff" },
  { id: "diff.tab-footprint", label: "Footprint diff tab", area: "diff" },
  { id: "diff.stage", label: "Diff viewport", area: "diff" },
  { id: "confirm.root", label: "Confirm dialog", area: "confirm" },
  { id: "confirm.scrim", label: "Confirm backdrop", area: "confirm" },
  { id: "confirm.title", label: "Confirm title", area: "confirm" },
  { id: "confirm.body", label: "Confirm body", area: "confirm" },
  { id: "confirm.actions", label: "Confirm action row", area: "confirm" },
  { id: "confirm.confirm", label: "Confirm button", area: "confirm" },
  { id: "confirm.cancel", label: "Cancel button", area: "confirm" },
  { id: "shell.root", label: "App frame", area: "shell" },
  { id: "shell.content", label: "Page content column", area: "shell" },
  { id: "shell.library", label: "Active library repository", area: "shell" },
  { id: "shell.statusbar", label: "Bottom status bar", area: "shell" },
  // DESIGN MODE'S ARRANGE SURFACE (plan 1.5, Phase 3B). A new area, and an area rather than rows
  // under an existing one because these elements belong to the EDITOR OF the application rather
  // than to any surface in it: they exist only while arrange is on, they sit in a portal over
  // whatever route is open, and an override written for one of them must never be confused with an
  // override written for the workspace underneath.
  //
  // The Design PANEL's own chrome is deliberately still outside the id system (see the header of
  // `components/DevPanel.tsx`), with three exceptions that earn a row: the switch that turns arrange
  // on, and the two blocks that are the only way back from an edit that took a piece off the screen
  // or out of storage. Those are the controls a screenshot of a broken arrangement has to be able
  // to name.
  { id: "design.edit-toggle", label: "Arrange mode switch", area: "design" },
  { id: "design.arrange", label: "Arrange section", area: "design" },
  { id: "design.arrange-state", label: "Whether the arrangement carries an edit", area: "design" },
  { id: "design.arrange-reset", label: "Back to the committed arrangement", area: "design" },
  { id: "design.arrange-restore", label: "Put one off-screen piece back", area: "design" },
  { id: "design.arrange-drafts", label: "Named local drafts", area: "design" },
  { id: "design.arrange-draft-name", label: "Draft name field", area: "design" },
  { id: "design.arrange-draft-save", label: "Store the arrangement under a name", area: "design" },
  { id: "design.arrange-draft", label: "One stored draft", area: "design" },
  // The canvas. Every one of these is drawn in a portal over the running application, one per
  // rendered placement, so each is a SHARED role in the same sense a part row is: an edit keyed on
  // it is meant to reach all of them.
  { id: "design.placement-handle", label: "One placement's drag handle", area: "design" },
  { id: "design.placement-resize", label: "One placement's resize handle", area: "design" },
  { id: "design.drop-target", label: "One legal drop position", area: "design" },
  { id: "design.piece-menu", label: "Piece settings menu", area: "design" },
  { id: "design.piece-name", label: "Which piece the menu is about", area: "design" },
  { id: "design.piece-collapse", label: "Collapse or expand one placement", area: "design" },
  { id: "design.piece-hide", label: "Hide or show one placement", area: "design" },
  { id: "design.piece-restore", label: "Restore one placement", area: "design" },
  { id: "design.piece-move-up", label: "One position earlier", area: "design" },
  { id: "design.piece-move-down", label: "One position later", area: "design" },
  { id: "design.piece-move-into", label: "Send a placement to another region", area: "design" },
  { id: "design.piece-position", label: "Free placement coordinates", area: "design" },
  { id: "design.piece-position-note", label: "Structural positioning restriction", area: "design" },
  { id: "design.piece-grid-slot", label: "Declared grid slot", area: "design" },
  // The narrow style scope (plan 1.5). The WIDE scope - a role everywhere it appears - is the Tokens
  // rows and the Box tab, which are outside the id system with the panel's other chrome; these two
  // are on the canvas beside the move controls and belong with them.
  { id: "design.piece-text-role", label: "Which text role this placement overrides", area: "design" },
  { id: "design.piece-text-role-here", label: "The role that placement takes here alone", area: "design" },
  // THE ISSUES LIST (plan 1.4). It earns rows on the same ground the Arrange section's do: it is the
  // surface a screenshot of a bad arrangement has to be able to name, and it is the one place a
  // committed layout's known cost is readable. The row id is SHARED across every reported issue, the
  // way the canvas ids are, because a style written for one row is meant for all of them.
  { id: "design.issues", label: "Issues section", area: "design" },
  { id: "design.issues-count", label: "The count of warnings and notes here", area: "design" },
  { id: "design.issue", label: "One reported issue", area: "design" },
  // The live letter-rule warning on the copy editor (plan 1.5). The Copy editor is otherwise the
  // panel's own chrome and outside the id system; this line is the exception because it is the one
  // part of it that states a RULE about the product rather than a control of the editor.
  { id: "design.letter-rule-warn", label: "Live letter-rule warning on a reworded label", area: "design" },
  { id: "design.pan-cue", label: "Canvas framing and pan cue", area: "design" },
];

// The areas in first-appearance order, for grouping the catalogue.
export const DEV_ID_AREAS: readonly string[] = ["rail", "about", "onboarding", "toast", "capture", "components", "projects", "component-browser", "detail", "search", "addpart", "ingest", "stm", "settings", "altiumdb", "complete", "preview", "diff", "confirm", "shell", "design"];

// A by-id lookup so consumers resolve an entry in one call instead of re-scanning the list.
export const DEV_ID_BY_ID: ReadonlyMap<string, DevIdEntry> = new Map(
  DEV_IDS.map((entry) => [entry.id, entry]),
);
