/**
 * The catalogue of stable dev-mode element ids: one row per meaningful area/element in the app. This is
 * the single source of truth for the ID system (mirroring lib/copy.tsx's id convention). Each element in
 * the app carries a `data-dev-id` whose value is one of these ids (dot-namespaced `area.element`,
 * lowercase-kebab per segment; the first segment is the area). Dev mode's inspect surface, the "Show IDs"
 * overlay, and the searchable catalogue all read this list, and later phases (per-element override, layout)
 * key their committed overrides on these same ids. Generated from the parallel-scout blueprint; keep it in
 * sync with the `data-dev-id` attributes in source (the parity test enforces it).
 */
export interface DevIdEntry {
  // The stable id, e.g. "detail.spec-sheet". Its first dot-segment is the area.
  id: string;
  // A short human label for the catalogue + the inspect badge.
  label: string;
  // The area (first id segment), for grouping the catalogue.
  area: string;
}

export const DEV_IDS: DevIdEntry[] = [
  { id: "rail.root", label: "Navigation rail", area: "rail" },
  { id: "rail.wordmark", label: "Wordmark tile", area: "rail" },
  { id: "rail.nav", label: "Primary nav group", area: "rail" },
  { id: "rail.nav-components", label: "Components nav item", area: "rail" },
  { id: "rail.nav-projects", label: "Projects nav item", area: "rail" },
  { id: "rail.nav-stm", label: "STM Viewer nav item", area: "rail" },
  { id: "rail.footer", label: "Rail footer", area: "rail" },
  { id: "rail.nav-settings", label: "Settings nav item", area: "rail" },
  { id: "rail.about", label: "About button", area: "rail" },
  { id: "rail.collapse", label: "Collapse rail toggle", area: "rail" },
  { id: "rail.utility", label: "Update + theme utility row", area: "rail" },
  { id: "rail.update", label: "Update / up-to-date control", area: "rail" },
  { id: "rail.theme-toggle", label: "Theme toggle", area: "rail" },
  { id: "about.root", label: "About dialog", area: "about" },
  { id: "about.scrim", label: "About backdrop", area: "about" },
  { id: "about.icon", label: "About logo tile", area: "about" },
  { id: "about.title", label: "About title", area: "about" },
  { id: "about.credit", label: "About credit line", area: "about" },
  { id: "about.stale", label: "About stale-frontend note", area: "about" },
  { id: "about.close", label: "Close About", area: "about" },
  { id: "about.links", label: "About social links", area: "about" },
  { id: "components.root", label: "Components page", area: "components" },
  { id: "components.picker", label: "Parts picker column", area: "components" },
  { id: "components.list-title", label: "Parts list title strip", area: "components" },
  { id: "components.add-parts", label: "Add Parts button", area: "components" },
  { id: "components.list-scroll", label: "Parts list scroll area", area: "components" },
  { id: "components.detail-pane", label: "Detail viewport column", area: "components" },
  { id: "components.empty", label: "Empty library state", area: "components" },
  { id: "components.select-prompt", label: "No-selection prompt", area: "components" },
  { id: "projects.root", label: "Projects page", area: "projects" },
  { id: "projects.picker", label: "Project picker column", area: "projects" },
  { id: "projects.list-title", label: "Project list title strip", area: "projects" },
  { id: "projects.workspace", label: "Selected project workspace", area: "projects" },
  { id: "projects.title-strip", label: "Project title strip", area: "projects" },
  { id: "projects.tabs", label: "Project tool tabs", area: "projects" },
  { id: "projects.tab-overview", label: "Overview tab", area: "projects" },
  { id: "projects.tab-bom", label: "BOM tab", area: "projects" },
  { id: "projects.tab-build", label: "Build tab", area: "projects" },
  { id: "projects.tab-activity", label: "Activity tab", area: "projects" },
  { id: "projects.overview", label: "Overview workbench", area: "projects" },
  { id: "projects.bom", label: "BOM workbench", area: "projects" },
  { id: "projects.build", label: "Build workbench", area: "projects" },
  { id: "projects.activity", label: "Activity workbench", area: "projects" },
  { id: "projects.placement-stage", label: "Placement map", area: "projects" },
  { id: "projects.board-control", label: "PCB board control", area: "projects" },
  { id: "projects.document-control", label: "Project document control", area: "projects" },
  { id: "projects.bom-filter-control", label: "BOM filter control", area: "projects" },
  { id: "projects.bom-line-control", label: "BOM line control", area: "projects" },
  { id: "projects.build-placement-control", label: "Build placement control", area: "projects" },
  { id: "projects.native-board-render", label: "Native PCB render", area: "projects" },
  { id: "components.finder", label: "Search + facet finder", area: "components" },
  { id: "components.search-box", label: "Search box", area: "components" },
  { id: "components.search-input", label: "Search input", area: "components" },
  { id: "components.filter-button", label: "Filters button", area: "components" },
  { id: "components.filter-panel", label: "Filters popover", area: "components" },
  { id: "components.filter-complete", label: "Complete-only toggle", area: "components" },
  { id: "components.filter-duplicates", label: "Duplicates toggle", area: "components" },
  { id: "components.filter-categories", label: "Category facet list", area: "components" },
  { id: "components.list", label: "Grouped parts list", area: "components" },
  { id: "components.category-header", label: "Category group header", area: "components" },
  { id: "components.row", label: "Part row", area: "components" },
  { id: "components.row-thumbnail", label: "Row thumbnail tile", area: "components" },
  { id: "components.row-duplicate", label: "Duplicate badge", area: "components" },
  { id: "components.row-warn", label: "Incomplete warning icon", area: "components" },
  { id: "components.workspace-band", label: "Open component tab band", area: "components" },
  // The opened component. Per-COMPONENT ids are dynamic (`component-browser.component[<id>]`,
  // its `.tab`, `.representation[<kind>]`, and `.provider[<provider id>]`), built by
  // lib/componentDevIds.ts, so they carry no catalogue row: the set is the library and the
  // provider registry, not a fixed list.
  { id: "component-browser.root", label: "Opened component workspace", area: "component-browser" },
  { id: "component-browser.tabs", label: "Open component tabs", area: "component-browser" },
  { id: "component-browser.close-tab", label: "Close the active component tab", area: "component-browser" },
  { id: "component-browser.delete", label: "Delete Part action", area: "component-browser" },
  { id: "component-browser.empty", label: "No component open", area: "component-browser" },
  { id: "component-browser.message", label: "Workspace loading / failure message", area: "component-browser" },
  { id: "component-browser.header", label: "Persistent identity header", area: "component-browser" },
  { id: "component-browser.header-name", label: "Component display name", area: "component-browser" },
  { id: "component-browser.header-status", label: "KiCad / Altium compact status", area: "component-browser" },
  { id: "component-browser.header-links", label: "Datasheet and provider links", area: "component-browser" },
  { id: "component-browser.header-datasheet", label: "Datasheet action", area: "component-browser" },
  { id: "component-browser.header-product-link", label: "Product page link", area: "component-browser" },
  { id: "component-browser.header-action", label: "Contextual primary action", area: "component-browser" },
  { id: "component-browser.dock", label: "Representation dock", area: "component-browser" },
  { id: "component-browser.layout.all", label: "Show every representation", area: "component-browser" },
  { id: "component-browser.layout.symbol", label: "Expand the symbol", area: "component-browser" },
  { id: "component-browser.layout.footprint", label: "Expand the footprint", area: "component-browser" },
  { id: "component-browser.layout.model", label: "Expand the 3D model", area: "component-browser" },
  { id: "component-browser.representation-title", label: "Representation name control", area: "component-browser" },
  { id: "component-browser.representation-rail", label: "Collapsed representation rail", area: "component-browser" },
  { id: "component-browser.representation-tool", label: "Representation tool choice", area: "component-browser" },
  { id: "component-browser.representation-preview", label: "Representation preview stage", area: "component-browser" },
  { id: "component-browser.representation-expand", label: "Expand a representation", area: "component-browser" },
  { id: "component-browser.representation-details", label: "Representation details", area: "component-browser" },
  { id: "component-browser.representation-issue", label: "Representation issue line", area: "component-browser" },
  { id: "component-browser.info", label: "Information tab region", area: "component-browser" },
  { id: "component-browser.info.tabs", label: "Information tab bar", area: "component-browser" },
  { id: "component-browser.info.tab-overview", label: "Overview tab", area: "component-browser" },
  { id: "component-browser.info.tab-specifications", label: "Specifications tab", area: "component-browser" },
  { id: "component-browser.info.tab-sourcing", label: "Sourcing tab", area: "component-browser" },
  { id: "component-browser.info.tab-sources", label: "Sources and history tab", area: "component-browser" },
  { id: "component-browser.description", label: "Description region", area: "component-browser" },
  { id: "component-browser.key-specs", label: "Key Specifications region", area: "component-browser" },
  { id: "component-browser.key-spec-pin", label: "Pin a key specification", area: "component-browser" },
  { id: "component-browser.attention", label: "Needs Attention region", area: "component-browser" },
  { id: "component-browser.attention-item", label: "One attention item", area: "component-browser" },
  { id: "component-browser.attention-action", label: "Attention item action", area: "component-browser" },
  { id: "component-browser.sourcing-snapshot", label: "Sourcing snapshot region", area: "component-browser" },
  { id: "component-browser.sourcing-snapshot-all", label: "View Full Sourcing", area: "component-browser" },
  { id: "component-browser.view-all", label: "View All action", area: "component-browser" },
  { id: "component-browser.specifications", label: "Specification groups region", area: "component-browser" },
  { id: "component-browser.specifications-all", label: "Full specification sheet", area: "component-browser" },
  { id: "component-browser.pinout", label: "Pinout region", area: "component-browser" },
  { id: "component-browser.spec-conflicts", label: "Specification disagreements region", area: "component-browser" },
  { id: "component-browser.sourcing", label: "Distributors region", area: "component-browser" },
  { id: "component-browser.sourcing-all", label: "Full sourcing sheet", area: "component-browser" },
  { id: "component-browser.relationships", label: "Related parts region", area: "component-browser" },
  { id: "component-browser.resources", label: "Provider documents region", area: "component-browser" },
  { id: "component-browser.sources", label: "Source records region", area: "component-browser" },
  { id: "component-browser.sources-all", label: "Full source ledger", area: "component-browser" },
  { id: "component-browser.field-sources", label: "Attributed fields region", area: "component-browser" },
  { id: "component-browser.diagnostics", label: "Projection diagnostics region", area: "component-browser" },
  { id: "component-browser.modal", label: "Component workspace modal", area: "component-browser" },
  { id: "component-browser.modal-close", label: "Close the workspace modal", area: "component-browser" },
  // The exhaustive sheets the compact tabs hand off to. Everything below lives INSIDE the one
  // workspace modal, which is the only surface in the opened component allowed to scroll.
  { id: "component-browser.spec-sheet", label: "Full specification sheet", area: "component-browser" },
  { id: "component-browser.spec-search", label: "Search specifications", area: "component-browser" },
  { id: "component-browser.spec-sort", label: "Sort specifications", area: "component-browser" },
  { id: "component-browser.spec-group", label: "One specification group", area: "component-browser" },
  { id: "component-browser.spec-row", label: "One specification row", area: "component-browser" },
  { id: "component-browser.spec-row-pin", label: "Pin a specification from the sheet", area: "component-browser" },
  { id: "component-browser.spec-alternate", label: "An alternate value for a specification", area: "component-browser" },
  { id: "component-browser.pinout-table", label: "Complete pinout table", area: "component-browser" },
  { id: "component-browser.pinout-lookup", label: "Look up a pinout", area: "component-browser" },
  { id: "component-browser.pinout-apply", label: "Apply Pinout action", area: "component-browser" },
  { id: "component-browser.sourcing-sheet", label: "Full sourcing sheet", area: "component-browser" },
  { id: "component-browser.source-state", label: "One source's outcome", area: "component-browser" },
  { id: "component-browser.offer", label: "One distributor offer", area: "component-browser" },
  { id: "component-browser.offer-ladder", label: "One offer's price ladder", area: "component-browser" },
  { id: "component-browser.sourcing-shared", label: "Trade and compliance facts", area: "component-browser" },
  { id: "component-browser.relationship-group", label: "One distributor-suggested relationship group", area: "component-browser" },
  { id: "component-browser.relationship-item", label: "One suggested related part", area: "component-browser" },
  { id: "component-browser.resource-link", label: "One provider document link", area: "component-browser" },
  { id: "component-browser.sources-sheet", label: "Full sources and history sheet", area: "component-browser" },
  { id: "component-browser.sources.tabs", label: "Sources and history tab bar", area: "component-browser" },
  { id: "component-browser.sources.tab-fields", label: "Field Sources tab", area: "component-browser" },
  { id: "component-browser.sources.tab-records", label: "Source Records tab", area: "component-browser" },
  { id: "component-browser.sources.tab-changes", label: "Changes tab", area: "component-browser" },
  { id: "component-browser.sources.tab-diagnostics", label: "Diagnostics tab", area: "component-browser" },
  { id: "component-browser.field-source-row", label: "One attributed field", area: "component-browser" },
  { id: "component-browser.field-source-apply", label: "Put an alternate value in force", area: "component-browser" },
  { id: "component-browser.source-record-row", label: "One captured source record", area: "component-browser" },
  { id: "component-browser.source-refresh", label: "Refresh Sourcing action", area: "component-browser" },
  { id: "component-browser.enrich", label: "Source lookup panel", area: "component-browser" },
  { id: "component-browser.change-entry", label: "One commit in the component timeline", area: "component-browser" },
  { id: "component-browser.diagnostics-toggle", label: "Show or hide diagnostics", area: "component-browser" },
  { id: "component-browser.diagnostics-raw", label: "Show or hide the canonical record", area: "component-browser" },
  // Complete Component: the whole provider trip for one component, inside the one workspace modal.
  // Which provider can supply the whole set, how to reach it, what has landed, and which retained
  // set is in force. Per-provider ROWS are dynamic and deliberately have no rows here.
  { id: "component-browser.providers-summary", label: "Complete Component action", area: "component-browser" },
  { id: "component-browser.complete-component", label: "Complete Component sheet", area: "component-browser" },
  { id: "component-browser.provider-matrix", label: "Provider coverage matrix", area: "component-browser" },
  { id: "component-browser.provider-open", label: "Open one provider", area: "component-browser" },
  { id: "component-browser.provider-assert", label: "Your answer for one artifact", area: "component-browser" },
  { id: "component-browser.provider-browser", label: "Provider trip controls", area: "component-browser" },
  { id: "component-browser.provider-show", label: "Show the provider page", area: "component-browser" },
  { id: "component-browser.provider-return", label: "Return To Stockroom", area: "component-browser" },
  { id: "component-browser.provider-import", label: "Import downloaded files", area: "component-browser" },
  { id: "component-browser.provider-progress", label: "Download progress", area: "component-browser" },
  { id: "component-browser.provider-report", label: "Provider run report", area: "component-browser" },
  { id: "component-browser.provider-sets", label: "Retained verified sets", area: "component-browser" },
  { id: "component-browser.identity-edit", label: "Edit Identity action", area: "component-browser" },
  { id: "component-browser.identity-sheet", label: "Identity editing sheet", area: "component-browser" },
  { id: "component-browser.identity-field", label: "One editable identity field", area: "component-browser" },
  { id: "component-browser.identity-category", label: "Move this component to another category", area: "component-browser" },
  { id: "detail.root", label: "Detail panel", area: "detail" },
  { id: "detail.title-strip", label: "Detail title strip", area: "detail" },
  { id: "detail.identity", label: "Identity / specimen rail", area: "detail" },
  // The EDA handoff block at the head of the Specifications column. Per-field cell ids are
  // DERIVED (`detail.handoff-<field key>`) from the generated EDA registry, so a new registry
  // field brings its own cell id and this catalogue needs no edit.
  { id: "detail.handoff", label: "EDA handoff block", area: "detail" },
  { id: "detail.category-control", label: "Category selector", area: "detail" },
  { id: "detail.handoff-tab", label: "Handoff tab panel", area: "detail" },
  { id: "detail.representations", label: "Cross-EDA representation matrix", area: "detail" },
  { id: "detail.key-specs", label: "Key Specifications block", area: "detail" },
  { id: "detail.description-lede", label: "Description at the head of the specs column", area: "detail" },
  { id: "detail.specs-collapse", label: "Collapse the Specifications pane", area: "detail" },
  { id: "detail.specs-expand", label: "Expand the collapsed Specifications pane", area: "detail" },
  { id: "detail.sourcing-collapse", label: "Collapse the Sourcing pane", area: "detail" },
  { id: "detail.sourcing-expand", label: "Expand the collapsed Sourcing pane", area: "detail" },
  { id: "detail.specs-list", label: "Full specifications list", area: "detail" },
  { id: "detail.spec-pin", label: "Pin spec to Key Specifications", area: "detail" },
  { id: "detail.handoff-ready", label: "Handoff readiness count", area: "detail" },
  { id: "detail.title", label: "Part headline", area: "detail" },
  { id: "detail.canvas", label: "Part canvas / asset strip", area: "detail" },
  { id: "detail.model-spin", label: "3D idle-spin toggle", area: "detail" },
  { id: "detail.model-settings", label: "3D model settings toggle", area: "detail" },
  { id: "detail.model-settings-popover", label: "3D model settings panel", area: "detail" },
  { id: "detail.model-views", label: "3D canonical view switcher", area: "detail" },
  { id: "detail.model-board", label: "3D land-pattern (footprint) toggle", area: "detail" },
  { id: "detail.model-layers", label: "3D layer + shading bar", area: "detail" },
  { id: "detail.model-shading", label: "3D shading mode group", area: "detail" },
  { id: "detail.model-show-model", label: "3D layer: model", area: "detail" },
  { id: "detail.model-show-board", label: "3D layer: PCB substrate", area: "detail" },
  { id: "detail.model-shade-realistic", label: "3D shading: realistic", area: "detail" },
  { id: "detail.model-shade-studio", label: "3D shading: studio", area: "detail" },
  { id: "detail.model-shade-xray", label: "3D shading: x-ray", area: "detail" },
  { id: "detail.model-view-iso", label: "3D view: three-quarter", area: "detail" },
  { id: "detail.model-view-top", label: "3D view: top down", area: "detail" },
  { id: "detail.model-view-front", label: "3D view: front elevation", area: "detail" },
  { id: "detail.readiness", label: "KiCad / Altium readiness", area: "detail" },
  { id: "detail.complete-part", label: "Complete Part action", area: "detail" },
  { id: "detail.photo", label: "Detail photo trigger", area: "detail" },
  { id: "detail.remove-asset", label: "Remove element chip", area: "detail" },
  { id: "detail.embed3d", label: "Embed 3D Model action", area: "detail" },
  { id: "detail.embed3d-done", label: "3D Model embedded confirmation", area: "detail" },
  { id: "detail.embed3d-blocked", label: "Embed 3D Model blocked reason", area: "detail" },
  { id: "detail.tabs", label: "Workbench tab bar", area: "detail" },
  { id: "detail.tab-specs", label: "Specs tab", area: "detail" },
  { id: "detail.tab-sourcing", label: "Sourcing tab", area: "detail" },
  { id: "detail.tab-enrich", label: "Enrich tab", area: "detail" },
  { id: "detail.tab-history", label: "History tab", area: "detail" },
  { id: "detail.specs", label: "Specifications sheet", area: "detail" },
  { id: "detail.spec-group", label: "Spec group block", area: "detail" },
  {
    id: "detail.spec-group-toggle",
    label: "Spec group disclosure",
    area: "detail",
  },
  { id: "detail.spec-list", label: "Multi-option spec value", area: "detail" },
  { id: "detail.spec-family", label: "Repeated spec family row", area: "detail" },
  { id: "detail.alternates", label: "Other sources for a value", area: "detail" },
  { id: "detail.trade", label: "Trade and compliance block", area: "detail" },
  { id: "detail.sourcing", label: "Sourcing panel", area: "detail" },
  { id: "detail.sourcing-refresh", label: "Refresh Sourcing button", area: "detail" },
  { id: "detail.sourcing-nodata", label: "Vendor with no price or stock", area: "detail" },
  { id: "detail.pinout", label: "Pinout panel", area: "detail" },
  { id: "detail.pinout-list", label: "Datasheet pinout scroll region", area: "detail" },
  { id: "detail.enrich", label: "Enrich panel", area: "detail" },
  { id: "detail.history", label: "History timeline", area: "detail" },
  { id: "detail.delete", label: "Delete Part link", area: "detail" },
  { id: "search.root", label: "Search overlay", area: "search" },
  { id: "search.query", label: "Query field", area: "search" },
  { id: "search.query-input", label: "Query input", area: "search" },
  { id: "search.close", label: "Close button", area: "search" },
  { id: "search.subbar", label: "Results + chips + sort bar", area: "search" },
  { id: "search.result-count", label: "Result count", area: "search" },
  { id: "search.chips", label: "Active filter chips", area: "search" },
  { id: "search.sort", label: "Sort control", area: "search" },
  { id: "search.rail", label: "Facet rail", area: "search" },
  { id: "search.rail-category", label: "Category facet group", area: "search" },
  { id: "search.rail-facet", label: "Generated spec facet group", area: "search" },
  { id: "search.single-value-facet", label: "Single-value facet", area: "search" },
  { id: "search.rail-instock", label: "In Stock toggle", area: "search" },
  { id: "search.results", label: "Results table container", area: "search" },
  { id: "search.results-table", label: "Results table", area: "search" },
  { id: "search.results-row", label: "Result row", area: "search" },
  { id: "search.footer", label: "Keyboard-hints footer", area: "search" },
  { id: "addpart.root", label: "Add-a-Part dialog", area: "addpart" },
  { id: "addpart.scrim", label: "Add-a-Part backdrop", area: "addpart" },
  { id: "addpart.header", label: "Add-a-Part header", area: "addpart" },
  { id: "addpart.close", label: "Add-a-Part close", area: "addpart" },
  { id: "addpart.body", label: "Add-a-Part body", area: "addpart" },
  { id: "ingest.root", label: "Add-a-Part flow", area: "ingest" },
  { id: "ingest.hero", label: "Lookup hero", area: "ingest" },
  { id: "ingest.input", label: "Link / part-number input", area: "ingest" },
  { id: "ingest.kind-control", label: "Passive kind control", area: "ingest" },
  { id: "ingest.package-control", label: "Passive package control", area: "ingest" },
  { id: "ingest.lookup", label: "Look Up button", area: "ingest" },
  { id: "ingest.stages", label: "Enrichment stages", area: "ingest" },
  { id: "ingest.path", label: "Part path strip", area: "ingest" },
  { id: "ingest.passive", label: "Passive add card", area: "ingest" },
  { id: "ingest.blocked", label: "Blocked-fetch card", area: "ingest" },
  { id: "ingest.nonpassive", label: "Needs-files card", area: "ingest" },
  { id: "ingest.pulled-summary", label: "Pulled summary", area: "ingest" },
  { id: "ingest.pulled-photo", label: "Pulled photo trigger", area: "ingest" },
  { id: "ingest.pulled-specs", label: "Pulled specs table", area: "ingest" },
  { id: "ingest.staged", label: "Review and Add list", area: "ingest" },
  { id: "ingest.candidate", label: "Staged candidate card", area: "ingest" },
  { id: "ingest.footprint-control", label: "Candidate footprint control", area: "ingest" },
  { id: "ingest.candidate-add", label: "Candidate Add to Components action", area: "ingest" },
  { id: "ingest.candidate-photo", label: "Candidate photo trigger", area: "ingest" },
  { id: "ingest.candidate-conflicts", label: "Candidate spec conflicts", area: "ingest" },
  { id: "ingest.passive-add", label: "Passive Add to Components action", area: "ingest" },
  { id: "ingest.bulk", label: "Import A List panel", area: "ingest" },
  { id: "ingest.bulk-input", label: "Bulk part-number paste well", area: "ingest" },
  { id: "ingest.bulk-import", label: "Bulk import action", area: "ingest" },
  { id: "ingest.bulk-preview", label: "Bulk import dry run", area: "ingest" },
  { id: "ingest.bulk-progress", label: "Bulk import progress line", area: "ingest" },
  { id: "ingest.bulk-error", label: "Bulk import failure", area: "ingest" },
  { id: "ingest.bulk-result", label: "Bulk import report", area: "ingest" },
  { id: "ingest.bulk-toggle", label: "Bulk report row filter", area: "ingest" },
  { id: "stm.root", label: "STM Viewer page", area: "stm" },
  { id: "stm.pinout", label: "Single-MCU pinout workspace", area: "stm" },
  { id: "stm.bench", label: "Universal support workbench", area: "stm" },
  { id: "stm.target-set-control", label: "Target set control", area: "stm" },
  { id: "stm.target-definition", label: "Target definition workspace", area: "stm" },
  { id: "stm.socket-solution", label: "Socket solution workspace", area: "stm" },
  { id: "stm.target-map", label: "Physical package map", area: "stm" },
  { id: "stm.target-legend", label: "Interactive map legend", area: "stm" },
  { id: "stm.target-legend-guide", label: "Complete legend guide", area: "stm" },
  { id: "stm.target-inspector", label: "Physical position inspector", area: "stm" },
  { id: "stm.lens.compatibility", label: "Compatibility map lens", area: "stm" },
  { id: "stm.lens.foundation", label: "Run-critical map lens", area: "stm" },
  { id: "stm.lens.electrical", label: "Electrical-role map lens", area: "stm" },
  { id: "stm.lens.access", label: "Service-access map lens", area: "stm" },
  { id: "stm.lens.board", label: "Routing-plan map lens", area: "stm" },
  { id: "stm.inspector.decision", label: "Position decision view", area: "stm" },
  { id: "stm.inspector.targets", label: "Position MCU view", area: "stm" },
  { id: "stm.inspector.evidence", label: "Position evidence view", area: "stm" },
  { id: "settings.root", label: "Settings page", area: "settings" },
  { id: "settings.title", label: "Settings heading", area: "settings" },
  { id: "settings.machine-band", label: "Application delivery and machine readiness", area: "settings" },
  { id: "settings.nav", label: "Settings group nav", area: "settings" },
  { id: "settings.nav-general", label: "General settings group", area: "settings" },
  { id: "settings.nav-library", label: "Library group", area: "settings" },
  { id: "settings.nav-eda", label: "EDA Tools group", area: "settings" },
  { id: "settings.nav-maintenance", label: "Maintenance group", area: "settings" },
  { id: "settings.nav-sources", label: "Data Sources group", area: "settings" },
  { id: "settings.content", label: "Active settings group content", area: "settings" },
  { id: "settings.altium", label: "Altium Database Library section", area: "settings" },
  { id: "settings.cubemx", label: "STM32CubeMX Data section", area: "settings" },
  { id: "settings.appearance", label: "Appearance section", area: "settings" },
  { id: "settings.appearance-theme", label: "Theme toggle", area: "settings" },
  { id: "settings.profiles", label: "Component Profiles section", area: "settings" },
  { id: "settings.profiles-row", label: "Profile row", area: "settings" },
  { id: "settings.profiles-create", label: "Create profile row", area: "settings" },
  { id: "settings.sync", label: "Component Sync section", area: "settings" },
  { id: "settings.sync-action", label: "Pull And Push Library button", area: "settings" },
  { id: "settings.github", label: "GitHub section", area: "settings" },
  { id: "settings.github-token", label: "GitHub token input", area: "settings" },
  { id: "settings.kicad", label: "KiCad section", area: "settings" },
  { id: "settings.kicad-wire", label: "Recheck And Wire KiCad button", area: "settings" },
  { id: "settings.kicad-overrides", label: "KiCad override inputs", area: "settings" },
  { id: "settings.librarysync", label: "Library Sync settings group", area: "settings" },
  { id: "settings.library-lfs", label: "Where the library stores binary payloads", area: "settings" },
  { id: "settings.library-lfs.adopt", label: "Store the library binaries in Git LFS", area: "settings" },
  { id: "settings.library-hygiene", label: "Files the library shares that it should not", area: "settings" },
  { id: "settings.library-hygiene.sync", label: "Stop sharing the library per-user files", area: "settings" },
  { id: "settings.completion", label: "Library Completion section", area: "settings" },
  { id: "settings.completion-worklist", label: "What still needs a person", area: "settings" },
  { id: "settings.completion-worklist-row", label: "One provider trip for one component", area: "settings" },
  { id: "settings.completion-worklist-start", label: "Start this provider capture for this component", area: "settings" },
  { id: "settings.completion-worklist-run", label: "Work through every listed component in order", area: "settings" },
  { id: "settings.derivation", label: "Presentation Data section", area: "settings" },
  { id: "settings.cad-clear", label: "Clear CAD Files section", area: "settings" },
  { id: "settings.cad-clear.run", label: "Remove All CAD Files button", area: "settings" },
  { id: "settings.derivation.rebuild", label: "Recompute Presentation Data button", area: "settings" },
  { id: "settings.health", label: "Library Health section", area: "settings" },
  { id: "settings.health-repair", label: "Apply Safe Library Repairs button", area: "settings" },
  { id: "settings.rescan", label: "Procurement Rescan section", area: "settings" },
  { id: "settings.rescan-action", label: "Refresh Prices button", area: "settings" },
  { id: "settings.distributor", label: "Distributor APIs section", area: "settings" },
  { id: "settings.distributor-key", label: "Mouser key input", area: "settings" },
  { id: "settings.vendor-login-row", label: "API credential row", area: "settings" },
  { id: "settings.update", label: "Automatic Updates section", area: "settings" },
  { id: "altiumdb.section-progress", label: "DbLib ready meter", area: "altiumdb" },
  { id: "altiumdb.section-path", label: "DbLib install path row", area: "altiumdb" },
  { id: "altiumdb.section-odbc", label: "ODBC driver status + download", area: "altiumdb" },
  { id: "altiumdb.section-actions", label: "Regenerate / View Library", area: "altiumdb" },
  { id: "altiumdb.modal", label: "Altium DbLib modal", area: "altiumdb" },
  { id: "altiumdb.modal-filter", label: "DbLib filter control", area: "altiumdb" },
  { id: "altiumdb.modal-table", label: "DbLib parts table", area: "altiumdb" },
  { id: "altiumdb.setup-modal", label: "Altium setup guide modal", area: "altiumdb" },
  { id: "altiumdb.embed-all", label: "Embed every pending 3D model in one run", area: "altiumdb" },
  { id: "complete.root", label: "Complete Part dialog", area: "complete" },
  { id: "complete.header", label: "Complete Part header", area: "complete" },
  { id: "complete.cad", label: "CAD Files capture block", area: "complete" },
  { id: "complete.cad-checklist", label: "CAD capture checklist", area: "complete" },
  { id: "complete.cad-actions", label: "Get CAD Files buttons", area: "complete" },
  { id: "complete.cad-provider-outcomes", label: "CAD provider results", area: "complete" },
  { id: "complete.cad-live-status", label: "CAD capture live status", area: "complete" },
  { id: "complete.requirements", label: "Requirements list", area: "complete" },
  { id: "complete.requirement-row", label: "Requirement row", area: "complete" },
  { id: "complete.done", label: "Done button", area: "complete" },
  { id: "preview.root", label: "Preview dialog", area: "preview" },
  { id: "preview.header", label: "Preview header", area: "preview" },
  { id: "preview.close", label: "Preview close", area: "preview" },
  { id: "preview.stage", label: "Preview viewport", area: "preview" },
  { id: "detail.model-gizmo", label: "3D view cube", area: "detail" },
  { id: "preview.photo", label: "Product photo dialog", area: "preview" },
  { id: "preview.photo-count", label: "Photo carousel counter", area: "preview" },
  { id: "preview.photo-prev", label: "Photo carousel previous", area: "preview" },
  { id: "preview.photo-next", label: "Photo carousel next", area: "preview" },
  { id: "diff.root", label: "Diff dialog", area: "diff" },
  { id: "diff.header", label: "Diff header", area: "diff" },
  { id: "diff.tabs", label: "Diff type tabs", area: "diff" },
  { id: "diff.stage", label: "Diff viewport", area: "diff" },
  { id: "confirm.root", label: "Confirm dialog", area: "confirm" },
  { id: "confirm.scrim", label: "Confirm backdrop", area: "confirm" },
  { id: "confirm.title", label: "Confirm title", area: "confirm" },
  { id: "confirm.body", label: "Confirm body", area: "confirm" },
  { id: "confirm.actions", label: "Confirm action row", area: "confirm" },
  { id: "confirm.confirm", label: "Confirm button", area: "confirm" },
  { id: "confirm.cancel", label: "Cancel button", area: "confirm" },
  { id: "shell.root", label: "App frame", area: "shell" },
  { id: "shell.content", label: "Page content column", area: "shell" },
  { id: "shell.library", label: "Active library repository", area: "shell" },
  { id: "shell.statusbar", label: "Bottom status bar", area: "shell" },
];

// The areas in first-appearance order, for grouping the catalogue.
export const DEV_ID_AREAS: readonly string[] = ["rail", "about", "components", "projects", "component-browser", "detail", "search", "addpart", "ingest", "stm", "settings", "altiumdb", "complete", "preview", "diff", "confirm", "shell"];

// A by-id lookup so consumers resolve an entry in one call instead of re-scanning the list.
export const DEV_ID_BY_ID: ReadonlyMap<string, DevIdEntry> = new Map(
  DEV_IDS.map((entry) => [entry.id, entry]),
);
