/**
 * The catalogue of stable dev-mode element ids: one row per meaningful area/element in the app. This is
 * the single source of truth for the ID system (mirroring lib/copy.tsx's id convention). Each element in
 * the app carries a `data-dev-id` whose value is one of these ids (dot-namespaced `area.element`,
 * lowercase-kebab per segment; the first segment is the area). Dev mode's inspect surface, the "Show IDs"
 * overlay, and the searchable catalogue all read this list, and later phases (per-element override, layout)
 * key their committed overrides on these same ids. Generated from the parallel-scout blueprint; keep it in
 * sync with the `data-dev-id` attributes in source (the parity test enforces it).
 */
export interface DevIdEntry {
  // The stable id, e.g. "detail.spec-sheet". Its first dot-segment is the area.
  id: string;
  // A short human label for the catalogue + the inspect badge.
  label: string;
  // The area (first id segment), for grouping the catalogue.
  area: string;
}

export const DEV_IDS: DevIdEntry[] = [
  { id: "rail.root", label: "Navigation rail", area: "rail" },
  { id: "rail.wordmark", label: "Wordmark tile", area: "rail" },
  { id: "rail.nav", label: "Primary nav group", area: "rail" },
  { id: "rail.nav-components", label: "Components nav item", area: "rail" },
  { id: "rail.nav-projects", label: "Projects nav item", area: "rail" },
  { id: "rail.footer", label: "Rail footer", area: "rail" },
  { id: "rail.nav-settings", label: "Settings nav item", area: "rail" },
  { id: "rail.about", label: "About button", area: "rail" },
  { id: "rail.utility", label: "Update + theme utility row", area: "rail" },
  { id: "rail.update", label: "Update / up-to-date control", area: "rail" },
  { id: "rail.theme-toggle", label: "Theme toggle", area: "rail" },
  { id: "about.root", label: "About dialog", area: "about" },
  { id: "about.scrim", label: "About backdrop", area: "about" },
  { id: "about.icon", label: "About logo tile", area: "about" },
  { id: "about.title", label: "About title", area: "about" },
  { id: "about.credit", label: "About credit line", area: "about" },
  { id: "about.links", label: "About social links", area: "about" },
  { id: "components.root", label: "Components page", area: "components" },
  { id: "components.picker", label: "Parts picker column", area: "components" },
  { id: "components.add-parts", label: "Add Parts button", area: "components" },
  { id: "components.list-scroll", label: "Parts list scroll area", area: "components" },
  { id: "components.detail-pane", label: "Detail viewport column", area: "components" },
  { id: "components.empty", label: "Empty library state", area: "components" },
  { id: "components.select-prompt", label: "No-selection prompt", area: "components" },
  { id: "components.finder", label: "Search + facet finder", area: "components" },
  { id: "components.search-box", label: "Search box", area: "components" },
  { id: "components.search-input", label: "Search input", area: "components" },
  { id: "components.filter-button", label: "Filters button", area: "components" },
  { id: "components.filter-panel", label: "Filters popover", area: "components" },
  { id: "components.filter-complete", label: "Complete-only toggle", area: "components" },
  { id: "components.filter-duplicates", label: "Duplicates toggle", area: "components" },
  { id: "components.filter-categories", label: "Category facet list", area: "components" },
  { id: "components.list", label: "Grouped parts list", area: "components" },
  { id: "components.category-header", label: "Category group header", area: "components" },
  { id: "components.row", label: "Part row", area: "components" },
  { id: "components.row-thumbnail", label: "Row thumbnail tile", area: "components" },
  { id: "components.row-duplicate", label: "Duplicate badge", area: "components" },
  { id: "components.row-warn", label: "Incomplete warning icon", area: "components" },
  { id: "detail.root", label: "Detail panel", area: "detail" },
  { id: "detail.identity", label: "Identity / specimen rail", area: "detail" },
  { id: "detail.title", label: "Part headline", area: "detail" },
  { id: "detail.identity-line", label: "MPN + manufacturer line", area: "detail" },
  { id: "detail.canvas", label: "Part canvas / asset strip", area: "detail" },
  { id: "detail.asset-hero", label: "3D model hero tile", area: "detail" },
  { id: "detail.asset-symbol", label: "Symbol file card", area: "detail" },
  { id: "detail.asset-footprint", label: "Footprint file card", area: "detail" },
  { id: "detail.asset-stage", label: "Asset tile stage / chamber", area: "detail" },
  { id: "detail.readiness", label: "KiCad / Altium readiness", area: "detail" },
  { id: "detail.complete-part", label: "Complete Part action", area: "detail" },
  { id: "detail.reference", label: "Datasheet + notes block", area: "detail" },
  { id: "detail.datasheet-row", label: "Datasheet row", area: "detail" },
  { id: "detail.notes-row", label: "Notes row", area: "detail" },
  { id: "detail.workbench", label: "Workbench panel", area: "detail" },
  { id: "detail.tabs", label: "Workbench tab bar", area: "detail" },
  { id: "detail.tab-specs", label: "Specs tab", area: "detail" },
  { id: "detail.tab-sourcing", label: "Sourcing tab", area: "detail" },
  { id: "detail.tab-pinout", label: "Pinout tab", area: "detail" },
  { id: "detail.tab-enrich", label: "Enrich tab", area: "detail" },
  { id: "detail.tab-history", label: "History tab", area: "detail" },
  { id: "detail.attributes", label: "Attributes chips", area: "detail" },
  { id: "detail.specs", label: "Specifications sheet", area: "detail" },
  { id: "detail.spec-group", label: "Spec group block", area: "detail" },
  { id: "detail.sourcing", label: "Sourcing panel", area: "detail" },
  { id: "detail.pinout", label: "Pinout panel", area: "detail" },
  { id: "detail.enrich", label: "Enrich panel", area: "detail" },
  { id: "detail.history", label: "History timeline", area: "detail" },
  { id: "detail.footer", label: "Detail footer", area: "detail" },
  { id: "detail.filing", label: "Filing / category select", area: "detail" },
  { id: "detail.delete", label: "Delete Part link", area: "detail" },
  { id: "search.root", label: "Search overlay", area: "search" },
  { id: "search.query", label: "Query field", area: "search" },
  { id: "search.query-input", label: "Query input", area: "search" },
  { id: "search.close", label: "Close button", area: "search" },
  { id: "search.subbar", label: "Results + chips + sort bar", area: "search" },
  { id: "search.result-count", label: "Result count", area: "search" },
  { id: "search.chips", label: "Active filter chips", area: "search" },
  { id: "search.sort", label: "Sort control", area: "search" },
  { id: "search.rail", label: "Facet rail", area: "search" },
  { id: "search.rail-category", label: "Category facet group", area: "search" },
  { id: "search.rail-facet", label: "Generated spec facet group", area: "search" },
  { id: "search.rail-instock", label: "In Stock toggle", area: "search" },
  { id: "search.results", label: "Results table container", area: "search" },
  { id: "search.results-table", label: "Results table", area: "search" },
  { id: "search.results-row", label: "Result row", area: "search" },
  { id: "search.footer", label: "Keyboard-hints footer", area: "search" },
  { id: "addpart.root", label: "Add-a-Part dialog", area: "addpart" },
  { id: "addpart.scrim", label: "Add-a-Part backdrop", area: "addpart" },
  { id: "addpart.header", label: "Add-a-Part header", area: "addpart" },
  { id: "addpart.close", label: "Add-a-Part close", area: "addpart" },
  { id: "addpart.body", label: "Add-a-Part body", area: "addpart" },
  { id: "ingest.root", label: "Add-a-Part flow", area: "ingest" },
  { id: "ingest.hero", label: "Lookup hero", area: "ingest" },
  { id: "ingest.input", label: "Link / part-number input", area: "ingest" },
  { id: "ingest.lookup", label: "Look Up button", area: "ingest" },
  { id: "ingest.stages", label: "Enrichment stages", area: "ingest" },
  { id: "ingest.browse", label: "Browse for ZIP", area: "ingest" },
  { id: "ingest.passive", label: "Passive add card", area: "ingest" },
  { id: "ingest.blocked", label: "Blocked-fetch card", area: "ingest" },
  { id: "ingest.nonpassive", label: "Needs-files card", area: "ingest" },
  { id: "ingest.pulled-summary", label: "Pulled summary", area: "ingest" },
  { id: "ingest.progress", label: "Inspect progress bar", area: "ingest" },
  { id: "ingest.staged", label: "Review and Add list", area: "ingest" },
  { id: "ingest.candidate", label: "Staged candidate card", area: "ingest" },
  { id: "projects.root", label: "Projects page", area: "projects" },
  { id: "projects.picker", label: "Projects picker column", area: "projects" },
  { id: "projects.picker-title", label: "Projects heading", area: "projects" },
  { id: "projects.list", label: "Projects list", area: "projects" },
  { id: "projects.row", label: "Project row", area: "projects" },
  { id: "projects.register", label: "Register project bar", area: "projects" },
  { id: "projects.register-input", label: "Project path input", area: "projects" },
  { id: "projects.register-action", label: "Register button", area: "projects" },
  { id: "projects.detail", label: "Project detail column", area: "projects" },
  { id: "projects.detail-header", label: "Project detail header", area: "projects" },
  { id: "projects.remove", label: "Remove Project button", area: "projects" },
  { id: "projects.tabs", label: "Project tab bar", area: "projects" },
  { id: "projects.tab-overview", label: "Overview tab", area: "projects" },
  { id: "projects.tab-health", label: "Health tab", area: "projects" },
  { id: "projects.tab-bom", label: "BOM & Procurement tab", area: "projects" },
  { id: "projects.tab-setup", label: "PCB Setup tab", area: "projects" },
  { id: "projects.tab-netclasses", label: "Net Classes tab", area: "projects" },
  { id: "projects.buildability", label: "Buildability verdict", area: "projects" },
  { id: "projects.viewer", label: "Board viewer", area: "projects" },
  { id: "projects.audit", label: "Audit findings view", area: "projects" },
  { id: "projects.audit-chips", label: "Audit kind filter chips", area: "projects" },
  { id: "projects.audit-table", label: "Findings table", area: "projects" },
  { id: "projects.checks", label: "Rules Check (ERC/DRC)", area: "projects" },
  { id: "projects.prepare", label: "Prepare project", area: "projects" },
  { id: "projects.bom", label: "Build and cost", area: "projects" },
  { id: "projects.bom-exports", label: "BOM exports", area: "projects" },
  { id: "projects.revision-diff", label: "Revision diff", area: "projects" },
  { id: "projects.fab", label: "Fab prep", area: "projects" },
  { id: "projects.board-setup", label: "Board setup", area: "projects" },
  { id: "projects.pro-settings", label: "Design checks and variables", area: "projects" },
  { id: "projects.stackup", label: "Stackup", area: "projects" },
  { id: "projects.conform", label: "Object conform", area: "projects" },
  { id: "projects.fields", label: "Title-block fields", area: "projects" },
  { id: "projects.editor", label: "Net classes editor", area: "projects" },
  { id: "settings.root", label: "Settings page", area: "settings" },
  { id: "settings.title", label: "Settings heading", area: "settings" },
  { id: "settings.appearance", label: "Appearance section", area: "settings" },
  { id: "settings.appearance-theme", label: "Theme toggle", area: "settings" },
  { id: "settings.profiles", label: "Component Profiles section", area: "settings" },
  { id: "settings.profiles-row", label: "Profile row", area: "settings" },
  { id: "settings.profiles-create", label: "Create profile row", area: "settings" },
  { id: "settings.sync", label: "Component Sync section", area: "settings" },
  { id: "settings.sync-action", label: "Sync Now button", area: "settings" },
  { id: "settings.github", label: "GitHub section", area: "settings" },
  { id: "settings.github-token", label: "GitHub token input", area: "settings" },
  { id: "settings.kicad", label: "KiCad section", area: "settings" },
  { id: "settings.kicad-wire", label: "Wire KiCad button", area: "settings" },
  { id: "settings.kicad-overrides", label: "KiCad override inputs", area: "settings" },
  { id: "settings.health", label: "Library Health section", area: "settings" },
  { id: "settings.health-repair", label: "Repair Components button", area: "settings" },
  { id: "settings.rescan", label: "Procurement Rescan section", area: "settings" },
  { id: "settings.rescan-action", label: "Refresh Prices button", area: "settings" },
  { id: "settings.distributor", label: "Distributor (Mouser) section", area: "settings" },
  { id: "settings.distributor-key", label: "Mouser key input", area: "settings" },
  { id: "settings.vendor-logins", label: "Vendor Logins section", area: "settings" },
  { id: "settings.vendor-login-row", label: "Vendor login row", area: "settings" },
  { id: "settings.update", label: "App Update section", area: "settings" },
  { id: "settings.update-apply", label: "Apply Update button", area: "settings" },
  { id: "altiumdb.section", label: "Altium DbLib settings section", area: "altiumdb" },
  { id: "altiumdb.section-progress", label: "DbLib ready meter", area: "altiumdb" },
  { id: "altiumdb.section-path", label: "DbLib install path row", area: "altiumdb" },
  { id: "altiumdb.section-actions", label: "Regenerate / View Library", area: "altiumdb" },
  { id: "altiumdb.modal", label: "Altium DbLib modal", area: "altiumdb" },
  { id: "altiumdb.modal-filter", label: "DbLib filter control", area: "altiumdb" },
  { id: "altiumdb.modal-table", label: "DbLib parts table", area: "altiumdb" },
  { id: "altiumdb.modal-attach", label: "DbLib attach button", area: "altiumdb" },
  { id: "complete.root", label: "Complete Part dialog", area: "complete" },
  { id: "complete.header", label: "Complete Part header", area: "complete" },
  { id: "complete.cad", label: "CAD Files capture block", area: "complete" },
  { id: "complete.cad-checklist", label: "CAD capture checklist", area: "complete" },
  { id: "complete.cad-actions", label: "Get CAD Files buttons", area: "complete" },
  { id: "complete.requirements", label: "Requirements list", area: "complete" },
  { id: "complete.requirement-row", label: "Requirement row", area: "complete" },
  { id: "complete.done", label: "Done button", area: "complete" },
  { id: "preview.root", label: "Preview dialog", area: "preview" },
  { id: "preview.header", label: "Preview header", area: "preview" },
  { id: "preview.tabs", label: "Preview type tabs", area: "preview" },
  { id: "preview.close", label: "Preview close", area: "preview" },
  { id: "preview.stage", label: "Preview viewport", area: "preview" },
  { id: "diff.root", label: "Diff dialog", area: "diff" },
  { id: "diff.header", label: "Diff header", area: "diff" },
  { id: "diff.tabs", label: "Diff type tabs", area: "diff" },
  { id: "diff.stage", label: "Diff viewport", area: "diff" },
  { id: "confirm.root", label: "Confirm dialog", area: "confirm" },
  { id: "confirm.scrim", label: "Confirm backdrop", area: "confirm" },
  { id: "confirm.title", label: "Confirm title", area: "confirm" },
  { id: "confirm.body", label: "Confirm body", area: "confirm" },
  { id: "confirm.actions", label: "Confirm action row", area: "confirm" },
  { id: "confirm.confirm", label: "Confirm button", area: "confirm" },
  { id: "confirm.cancel", label: "Cancel button", area: "confirm" },
  { id: "shell.root", label: "App frame", area: "shell" },
  { id: "shell.content", label: "Page content column", area: "shell" },
  { id: "shell.drop-overlay", label: "Drag-and-drop overlay", area: "shell" },
];

// The areas in first-appearance order, for grouping the catalogue.
export const DEV_ID_AREAS: readonly string[] = ["rail", "about", "components", "detail", "search", "addpart", "ingest", "projects", "settings", "altiumdb", "complete", "preview", "diff", "confirm", "shell"];

// A by-id lookup so consumers resolve an entry in one call instead of re-scanning the list.
export const DEV_ID_BY_ID: ReadonlyMap<string, DevIdEntry> = new Map(
  DEV_IDS.map((entry) => [entry.id, entry]),
);
